### ISSUE TITLE
[feat] Size and/or time limit on logs

### ISSUE THREAD

**Issue by cbho** [zwave-js/zwavejs2mqtt#298] opened 2021-01-21 09:07 UTC
**Is your feature request related to a problem? Please describe.**
Not really a problem - just a suggestion.

**Describe the solution you'd like**
The latest improvement with moving logs to the persisting volumes in Docker and now being able to handle logs in the GUI is absolutely fantastic!
That has also lead me to notice the size of the logs - especially the z-wave log can really grow big.

I guess most people don't really need log files that are one-two-three weeks long.

A feature to automatically delete oldest entries, eihter based on log file size or time would prevent congestion caused by enourmous log files (that I guess most will also not remember to look into frequently).

**Describe alternatives you've considered**
Making a new log file everytime the system is restarted or every day would make it easier to delete stuff, if it cannot be done automatically.

**Comment by robertsLando** [comment] 2021-01-21 09:22
@cbho Why not use logrotate for that?

**Comment by robertsLando** [comment] 2021-01-21 09:24
@cbho log to file should be enabled only when you want to debug things, that should never be enabled by default

**Comment by cbho** [comment] 2021-01-21 10:36
@robertsLando:
Re: logrotate:
Because I didn't know about it ;-) (I'm only an happy amateur trying to find my way around ;-))

But, on a more serious note: 
It seems like zwavejs2mqtt might reach a lot of people (as proposed in this topic in the [Home Assistant forum](https://community.home-assistant.io/t/can-we-revisit-the-move-to-qt-openzwave/262612)).
Inevitably, with a potential increase in user base like that, it will lead to a lot of users who has only basic knowledge about the underlying systems (like me) and will make all the basic mistakes (like me) causing a lot of support requests.
Adding "safety measures" like that might decrease the risk of the developers drowning in "basic" support requests leaving time for development ;-)

Another way around could be an additional setting:
When activating "log to file" you have specifiy for how long (including indefinitely, if you really want it) and then disabling the logging to file after the given interval.

Only a suggestion - and of course, focusing on stability etc. is absolutely the most important thing - and thank you for all the hard work you (and others) - it is highly appreciated!

Chr.

**Comment by robertsLando** [comment] 2021-01-21 10:41
> It seems like zwavejs2mqtt might reach a lot of people (as proposed in this topic in the Home Assistant forum).
Inevitably, with a potential increase in user base like that, it will lead to a lot of users who has only basic knowledge about the underlying systems (like me) and will make all the basic mistakes (like me) causing a lot of support requests.

**Comment by cpk1** [comment] 2021-01-30 06:48
A simple thing could be to pop an alert or help text to let the user know without extra configuration their logfiles will keep growing?
Happy to look at some simple log file controls as well - I haven't looked closely yet at how they are managed though :P

**Comment by robertsLando** [comment] 2021-06-16 07:12
Duplicate of #1158

**Closed by robertsLando** 2021-06-16 07:12 UTC
Labels: enhancement
