### ISSUE TITLE
[feat] Export/Import device configuration

### ISSUE THREAD

**Issue by kdknigga** [zwave-js/zwavejs2mqtt#2056] opened 2021-12-14 16:12 UTC
Some device models (particularly Aeotec and Inovelli products) have so many configuration options, which is good, but it makes it a chore to get all of the config settings just the way you want them.  And then, after I spend a bunch of time configuring a device, let's say an LZW31-SN, if I have to exclude and reinclude the device for some reason I have to spend that time again getting the settings back to where they were.  Or, if I add an additional LZW31-SN, I bring up the configs for both and point-by-point make the new one configured the same as the existing one.

A mechanism to export and import a device's configuration, probably at least all of command class 112 and maybe also 132, would solve for both the backup use case and also the "make this device look like that device" use case.  Additionally, a way to schedule exports (or at least programmatically trigger them) would make backups even easier.

I saw #1942, but I'm not sure we're talking about the same thing.

Thanks a lot for considering!

**Comment by robertsLando** [comment] 2021-12-14 16:32
Duplicate of #1918 . Follow updates there

**Closed by robertsLando** 2021-12-14 16:32 UTC
Labels: enhancement

**Comment by kdknigga** [comment] 2021-12-14 16:33
Oh, I didn't see that one.  Sorry about that.

**Comment by robertsLando** [comment] 2021-12-14 16:35
No worries :) This helps me to know where I need to focus, if it's so demanded I will give that more priority

**Comment by robertsLando** [comment] 2021-12-14 16:36
@kdknigga BTW right now you could do that using a driver function if you are interested doing some experiment with that.
