### ISSUE TITLE
[bug] Notification sensor for basic command not created after re-interview

### ISSUE THREAD

**Issue by towerhand** [zwave-js/zwavejs2mqtt#1024] opened 2021-04-09 00:32 UTC
### Version

2021.4.1

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt: 3.2.0
zwave-js: 7.1.1

### Describe the bug

After re-interviewing my two GE switches the double click feature stopped working, the switches in question are a GE dimmer 14294 and a GE fan switch 14287 with the compat flag ```"treatBasicSetAsEvent": true```, node 16 and 17.

I'm using the MQTT discovery and when I go to the "home assistant" tab in each device the entities for the notifications are gone so it explains why the event is not getting published to MQTT, using the debug tool in zjs2m I was able to rule out a problem with zwavejs because the events are getting received.

I'm not sure when this bug started since the nodes don't get interviewed after every restart now.

### Expected behavior

An entity used to be created for the basic notification and zjs2m used to publish the value of "0" or "255" to MQTT.

### Additional context

Created new logs, re-interviewed node 17 and double clicked on both switches.
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6282338/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment] 2021-04-09 06:15
@AlCalzone ?

**Comment by AlCalzone** [comment] 2021-04-09 09:10
@towerhand loglevel "debug" please.

**Comment by AlCalzone** [comment] 2021-04-09 09:13
I guess you're looking for the wrong event in HA. There were breaking changes:
https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes

**Comment by towerhand** [comment] 2021-04-09 12:11
I’m using MQTT discovery, not using the zwave js server so that breaking changes shouldn’t affect me, I checked with freshcoast in discord and it is working with the zwaje js server, only in the mqtt side the entity disappears and stop reporting it.

I’ll post more logs in a little while, not sure what happened but I changed the settings to debug before recreating the logs.

**Comment by towerhand** [comment] 2021-04-09 12:51
Ok my apologies, I forgot I needed to change the log options in two places, attached new logs. In the screenshot the entity that disappeared is sensor.master_bedroom_fan_notification_event.

<img width="994" alt="Screen Shot 2021-04-09 at 7 50 29 AM" src="https://user-images.githubusercontent.com/42445253/114182514-503e9980-9908-11eb-99aa-f8851e65066f.png">


[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6285792/zwavejs2mqtt-store.zip)

**Comment by AlCalzone** [comment] 2021-04-09 14:01
Looks good from the `node-zwave-js` side - especially since it is working in `zwave-js-server`

**Comment by robertsLando** [comment] 2021-04-09 14:25
@towerhand Did you checked if you get them using mqtt explorer?

**Comment by towerhand** [comment] 2021-04-09 14:34
Yes, I checked with MQTT explorer and no topics are getting sent,  makes sense because zjs2m is not showing them in the UI as you can see in the screenshot, that device used to have 4 entities but sensor.master_bedroom_fan_notification_event disappeared.

**Comment by robertsLando** [comment] 2021-04-09 14:45
> makes sense because zjs2m is not showing them in the UI as you can see in the screenshot

It could be that them are sent as notificaitons, so in that case you would not see a valueId on ui for them

**Comment by towerhand** [comment] 2021-04-09 14:46
Ok, anything else I can do to test? or let me know if I can provide any more info.

**Comment by AlCalzone** [comment] 2021-04-09 14:51
@robertsLando the basic event is a `value notification` (so many similar names 😅)

**Comment by robertsLando** [comment] 2021-04-09 14:56
Ok I have just checked the code, I never changed anything on that side: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/Gateway.js#L1882

Here is where the discovery should happen, sincerly I have no clue as I also don't see any error on console. @billiaz ?

**Comment by towerhand** [comment] 2021-04-11 13:30
Could this be part of the reason? the basic option shows up as undefined.

<img width="994" alt="Screen Shot 2021-04-11 at 8 28 58 AM" src="https://user-images.githubusercontent.com/42445253/114306026-1ef8d180-9aa0-11eb-947a-c19222740803.png">

**Comment by towerhand** [comment] 2021-04-11 13:44
And this is part of the debug info tab in the device, the values I used to get when the entity was available before re interviewing were 0 and 255.

    {
      "id": "17-32-0-currentValue",
      "nodeId": 17,
      "commandClass": 32,
      "commandClassName": "Basic",
      "endpoint": 0,
      "property": "currentValue",
      "propertyName": "currentValue",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Current value",
      "stateless": false,
      "min": 0,
      "max": 99,
      "list": false,
      "isCurrentValue": true,
      "targetValue": "32-0-targetValue"
    },
    {
      "id": "17-32-0-targetValue",
      "nodeId": 17,
      "commandClass": 32,
      "commandClassName": "Basic",
      "endpoint": 0,
      "property": "targetValue",
      "propertyName": "targetValue",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Target value",
      "stateless": false,
      "min": 0,
      "max": 99,
      "list": false,
      "newValue": "",
      "toUpdate": true
    }

**Comment by AlCalzone** [comment] 2021-04-11 14:39
You won't see a status in that overview. The device configuration file tells zwave-js to treat the command as an **event** - to be specific `17-32-0-event`, which means that it only has a meaning the instant it is received.

Since these switches can send these events without changing their status, persisting them as a status would be incorrect.

@robertsLando I guess adding some documentation which specifies how zwavejs2mqtt handles the different events received from zwave-js would be good :)

**Comment by towerhand** [comment] 2021-04-11 22:14
Ah it makes sense, I was just trying to provide more info so hopefully you guys can figure out why zjs2m is not creating the entity and passing the event to mqtt.

**Comment by robertsLando** [comment] 2021-04-12 08:10
There is another issue related #1044

**Comment by towerhand** [comment] 2021-04-12 19:32
New logs  with latest master. @robertsLando 
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6299345/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment] 2021-04-13 07:07
Duplicate of https://github.com/zwave-js/zwavejs2mqtt/issues/1044. Please follow updates there ?

**Closed by robertsLando** 2021-04-13 07:07 UTC
Labels: bug
