### ISSUE TITLE
[bug] Scene notification not published to MQTT

### ISSUE THREAD

**Issue by bdbogjoe** [zwave-js/zwavejs2mqtt#471] opened 2021-02-05 17:46 UTC
### Version

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.1.0

### Describe the bug

Using Node 54 (Fibargroup | Dimmer 2 | FGD212) the scene is not published anymore to MQTT, was working fine in 1.0.0, but using current version or even 1.0.1 it does not work anymore

here the logs when working fine : 
[1.0.0.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5934305/1.0.0.zip)

zwave2mqtt     | 2021-02-05 18:43:52.541 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/sceneId: 14 with options { qos: 1, retain: false }
zwave2mqtt     | 2021-02-05 18:43:52.542 INFO ZWAVE: Node 54: value notification: 43-0-sceneId 14
zwave2mqtt     | 2021-02-05 18:43:52.545 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/dimmingDuration: Duration { unit: 'seconds', _value: 0, [value]: [Getter/Setter] } with options { qos: 1, retain: true }
zwave2mqtt     | 2021-02-05 18:43:52.547 INFO ZWAVE: Node 54: value updated: 43-0-dimmingDuration undefined => [Duration: 0seconds]
zwave2mqtt     | 2021-02-05 18:43:52.554 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/sceneId: undefined with options { qos: 1, retain: true }
zwave2mqtt     | 2021-02-05 18:43:52.555 INFO ZWAVE: Node 54: value updated: 43-0-sceneId undefined => undefined

and the logs when is does not work, i attached the logs for version 1.0.2
[1.0.2.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5934291/1.0.2.zip)

2021-02-05 16:44:41.680 INFO ZWAVE: Node 54: value notification: 43-0-sceneId 14
2021-02-05 16:44:41.691 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/dimmingDuration: Duration { unit: 'seconds', _value: 0, [value]: [Getter/Setter] } with options { qos: 1, retain: true }
2021-02-05 16:44:41.686 INFO ZWAVE: Node 54: value added: 43-0-dimmingDuration => [Duration: 0seconds]
2021-02-05 16:44:41.688 INFO ZWAVE: Node 54: value added 54-43-0-dimmingDuration => [Duration: 0seconds]

**Comment by robertsLando** [comment] 2021-02-05 17:55
@billiaz is this the same issue of the other one? Maybe something about stateless values?

**Comment by billiaz** [comment] 2021-02-05 20:54
I am interested to also see what driver sends... do we have a mixed log, or driver is not involved in this?

**Comment by bdbogjoe** [comment] 2021-02-05 21:26
i attached all logs, open the zip

**Comment by mbrrg** [comment] 2021-02-07 16:41
I have the same problem using Fibaro Dimmer 2. Scene activation event shows in the Zwave log, no MQTT message published.

**Comment by billiaz** [comment] 2021-02-07 17:23
I have not yet been able to reproduce it with fibaro.  @mbrrg can you give more details?

**Comment by billiaz** [comment] 2021-02-07 17:27
@bdbogjoe i jave a dimmer2, how can i reproduce this? Is it notifying on physocal button press or other to reproduce this

**Comment by billiaz** [comment] 2021-02-07 17:59
@bdbogjoe @mbrrg @robertsLando I can confirm bug exists, with my dimmer 2 too.
I cannot test further as it is my Mail bedroom! and baby is there still. 

If the logs do not contain "silly" level logs from driver, we need to have at least this to get also the payload output.
I suspect dimming duration, works in "mistirious ways" compared to other notifications, and we need to pinpoint the flow issue causing this.

All in all. I noticed only one notification topic pushed, at end of dimming, without value.

**Comment by billiaz** [comment] 2021-02-07 18:16
I have checked the logs of @bdbogjoe  I see no issues on 1.0.0
I see a bit different behaviour between 1.0.0 and my 1.0.4

On 1.0.0 I see scene MQTT changes from `undefined` to object `{ 'value':0, 'unit': 'seconds'}` back to undefinied.

on 1.0.4 (my device) I see MQTT receive the same message whenever I press and hold the button. It does not retain it, which is the right thing to do.

As the scene part is a configuration setting. can be
1. a retained topic without Value is not stored
2. Works really nicely with just posting the message/event when happens and no second message afterwards

for point 2, example on my mqtt history:
![mqtt_scene_dimmer2](https://user-images.githubusercontent.com/4048920/107155459-d37b5780-6978-11eb-9db3-ec8948ea7883.jpg)

So my previous post is not really valid.

**Comment by mbrrg** [comment] 2021-02-07 21:01
```
2021-02-07 21:54:47.811 INFO ZWAVE: Node 46: value notification: 43-0-sceneId 26
2021-02-07 21:54:47.817 INFO ZWAVE: Node 46: value updated: 43-0-dimmingDuration [Duration: 0seconds] => [Duration: 0seconds]
21:54:47.831 CNTRLR « [Node 046] TODO: no handler for application command
2021-02-07 21:54:48.795 INFO ZWAVE: Node 46: value updated: 38-2-currentValue 0 => 99
```
There is no longer any message posted to ```xxx/yyy/zzz/43/0/sceneId```, only to ```xxx/yyy/zzz/43/0/dimmingDuration```.

**Comment by billiaz** [comment] 2021-02-08 10:12
@mbrrg I will check it soon too! as this is strange

**Comment by bdbogjoe** [comment] 2021-02-08 14:06
let me know if you need anything else, i'm available for testing any fix, thanks

**Comment by daballiemo** [comment] 2021-02-22 10:19
I think I have the same problem.
I have a number of FDG211 and FDG212 and have recently migrated to zwavejs2mqtt.

I see in the zwave log
 `10:14:34.112 CNTRLR « [Node 015] TODO: no handler for application command
10:14:35.488 CNTRLR « [Node 015] TODO: no handler for application command`

When I press the button that is connected to the second input, but nothing more.
Previously this would trigger a scene but with Zwavejs2mqtt I do not have anything in MQTT to trigger the scene. I guess the same behaviour as decribed above.

**Comment by bdbogjoe** [comment] 2021-02-22 12:00
i just tested with latest (1.2.2), we have still same issue

for info using FGS223 (double switch) scene is published, but not with FGD212 (dimmer)

**Comment by robertsLando** [comment] 2021-02-22 12:22
@AlCalzone any clue what could be wrong here? Seems like the valueId isn't created for that, but it was on old version, maybe a regression?

**Comment by AlCalzone** [comment] 2021-02-22 12:26
I need to see a zwave-js log of a re-interview of the affected devices.

**Comment by robertsLando** [comment] 2021-02-22 12:44
@bdbogjoe Could you provide it?

**Comment by daballiemo** [comment] 2021-02-22 12:44
This is a zwave-js log of a re-interview of Node 15 which in my case is a FDG211. Hope I cathed what you wanted. I put it in "silly" mode. Devices 13,14,20,21 and 22 are dead nodes that have to be replaced.
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6021971/zwavejs_1.log)

**Comment by AlCalzone** [comment] 2021-02-22 12:50
```
12:37:43.327 CNTRLR « [Node 015] node info received
                      supported CCs:
                      · Manufacturer Specific
                      · Version
                      · Configuration
                      · Association
                      · Multi Channel Association
                      · Multilevel Switch
                      · Firmware Update Meta Data
                      · All Switch
                      · Powerlevel
                      controlled CCs:
                      · Multilevel Switch
                      · Scene Activation
```
Scene Activation CC is not listed as supported, so we don't automatically create values for it.
So our only option is to react dynamically once the scene is triggered once.

**Comment by daballiemo** [comment] 2021-02-22 13:25
> So our only option is to react dynamically once the scene is triggered once.

Is this something I have to do?

**Comment by bdbogjoe** [comment] 2021-02-22 13:26
strange why was ok with 1.0.0 ? do you need anything else from my side ?

**Comment by AlCalzone** [comment] 2021-02-22 14:34
Could be due to https://github.com/zwave-js/node-zwave-js/pull/1207 maybe.
I don't know which zjs2m version includes that.

**Comment by bdbogjoe** [comment] 2021-02-22 15:36
hum don't know how to do this, how to get the command hex code ? where to put this file ?

**Comment by AlCalzone** [comment] 2021-02-22 15:46
I can do it, which firmware version does your device have?

**Comment by bdbogjoe** [comment] 2021-02-22 15:58
[node_54.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6023223/node_54.json.txt)

as i can see from UI firmware is 3.5

**Comment by daballiemo** [comment] 2021-02-22 15:59
> Could be due to [zwave-js/node-zwave-js#1207](https://github.com/zwave-js/node-zwave-js/pull/1207) maybe.

I use on/off switches also as dimmers, there is a difference between the physical world and how the inputs are being used. Usecase, a FGS212 (on/off) is used to dim a light attached to a FGD211 ...

**Comment by bdbogjoe** [comment] 2021-02-22 16:06
from my side, sometimes using dimmer FGD212 as single switch because i don't need dimmer feature

there is a flag in config to disable dimmer

**Comment by AlCalzone** [comment] 2021-02-22 16:38
@bdbogjoe can you test the branch from the linked PR to see if that helps?

**Comment by bdbogjoe** [comment] 2021-02-22 17:03
how can i test this modification ?

**Comment by robertsLando** [comment] 2021-02-22 17:06
Using Dockerfile.contrib

**Comment by bdbogjoe** [comment] 2021-02-22 17:19
i mean is there any branch which includes this fix of zwave-js inside zwavejs2mqtt ?

**Comment by AlCalzone** [comment] 2021-02-22 18:35
No

**Comment by bdbogjoe** [comment] 2021-02-23 08:37
with the new branch here the result : 

from UI  :

![image](https://user-images.githubusercontent.com/1301462/108818921-668fd080-75ba-11eb-897c-77d3f195752e.png)

Maybe the value should not be writable

And when i double click : 

2021-02-23 09:32:01.926 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/sceneId: 14 with options { qos: 1, retain: false }
2021-02-23 09:32:01.927 INFO ZWAVE: Node 54: value notification: 43-0-sceneId 14
2021-02-23 09:32:01.930 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/dimmingDuration: Duration { unit: 'seconds', _value: 0, [value]: [Getter/Setter] } with options { qos: 1, retain: true }
2021-02-23 09:32:01.931 INFO ZWAVE: Node 54: value updated: 43-0-dimmingDuration [Duration: 0seconds] => [Duration: 0seconds]
2021-02-23 09:32:02.930 DEBUG MQTT: Publishing to zwave/maison/escalier/lumiere-rampe/43/0/sceneId: undefined with options { qos: 1, retain: false }



The scene is now well published to MQTT, but it goes back to undefined just after, is it normal ?

**Comment by robertsLando** [comment] 2021-02-23 08:48
> The scene is now well published to MQTT, but it goes back to undefined just after, is it normal ?

If it is stateless (as I think) set it to undefined is made innternally by z2m to clear the state so you can detect the change

**Comment by AlCalzone** [comment] 2021-02-23 08:49
> Maybe the value should not be writable

That's a current limitation => https://github.com/zwave-js/node-zwave-js/issues/528

**Comment by daballiemo** [comment] 2021-02-23 12:00
So if I understand correctly, this update will correct problems for FDG212.
Does this have an effect on the FDG211 as well, or is it necessary to go down the "commandclassadd" way?

tia

**Comment by AlCalzone** [comment] 2021-02-23 12:51
If the problem with FGD211 was that it also just controls the CC, the PR should affect that device too.

**Comment by daballiemo** [comment] 2021-02-23 16:30
I just checked. I can see the same as @bdbogjoe on my FGD212, but nothing on my FGD211; not in UI or in zwave log.
![Screenshot 2021-02-23 at 17 25 31](https://user-images.githubusercontent.com/16369502/108874479-7a5c2680-75fc-11eb-9fdf-7be3c354b2d1.png)
![Screenshot 2021-02-23 at 17 25 58](https://user-images.githubusercontent.com/16369502/108874499-7f20da80-75fc-11eb-8d3a-f9dc322c57eb.png)

Because the majority of my switches is the FGD211 and I am using the scenes a lot its back to OZW for the moment I guess

**Comment by AlCalzone** [comment] 2021-02-23 16:42
Did you reinterview the affected device?

**Comment by daballiemo** [comment] 2021-02-23 16:45
> Did you reinterview the affected device?

yes, a couple of times. I will now first start another instance as a test enviroment with said FDG211 and a spare controller. Just not to lose out on WAF ;-)

**Comment by AlCalzone** [comment] 2021-02-23 16:51
And you are sure you're running the master branch of zwave-js? @bdbogjoe also had some problems earlier but got it to work.

**Comment by daballiemo** [comment] 2021-02-23 16:54
BTW thanks for all the help sofar. I think.. I am running the right version, started a new container this afternoon.
![Screenshot 2021-02-23 at 17 53 02](https://user-images.githubusercontent.com/16369502/108878106-33703000-7600-11eb-9dd5-498dd56c7408.png)
I am not an expert on this ;-)

**Comment by AlCalzone** [comment] 2021-02-23 16:56
@robertsLando?

**Comment by daballiemo** [comment] 2021-02-23 17:48
I started a new container with another controller and added the FDG211 with the same result as before. I re-interviewed the node (logging in attachment)
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6030895/zwavejs_1.log)

**Comment by bdbogjoe** [comment] 2021-02-23 18:03
unfortunately i don't have FDG211 to try myself

As it is the latest version of zwavejs2mqtt does not include this fix, we need to do custom build using master branch of node-zwave-js

**Comment by daballiemo** [comment] 2021-02-23 18:05
I will start a new bug report for my FDG211

**Comment by robertsLando** [comment] 2021-02-24 07:53
Try to update to latest 1.3.0 version

**Comment by daballiemo** [comment] 2021-02-24 08:41
I have updated to the latest version (docker: 1.3.0 in dashboard), I see scene information in debug, but no scene information in MQTT. Is there any logging I can provide?

**Comment by robertsLando** [comment] 2021-02-24 10:14
>  I see scene information in debug

Please upload log files as described in bug issue template

**Comment by daballiemo** [comment] 2021-02-24 11:18
@robertsLando, please find logfiles attached.
Actions performed:
1) re-interview of node 2 (FGD211)
2) single click of second switch (the one not carrying load)
3) double click of second switch
4) triple click of second switch

thanks in advance!
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6035514/zwavejs_1.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6035515/zwavejs2mqtt.log)

**Comment by AlCalzone** [comment] 2021-02-24 11:43
The values get received and published as events. But I'm not sure if zwavejs2mqtt sees the value ID, because
```
11:14:06.437 DRIVER   version 6.4.0
```

**Comment by daballiemo** [comment] 2021-02-24 11:57
@AlCalzone because version 6.4.0 is not the right version?

**Comment by AlCalzone** [comment] 2021-02-24 12:09
6.4.0 was released **before** the fix. I'm not sure if the docker image 1.3.0 was built with the master branch after the fix was merged 🤷🏻‍♂️

**Comment by daballiemo** [comment] 2021-02-24 12:27
Ok no big problem, I just have to wait till it pops up then I guess. When I see driver 6.5.0 then its included?

**Comment by AlCalzone** [comment] 2021-02-24 12:32
yep

**Comment by daballiemo** [comment] 2021-02-24 17:29
@AlCalzone, just respun my docker container. My driver version is now 6.5.0.
I now see the scene information in MQTT and I am able to catch it in HA. 
As soon as the message with the scene information arrives, its overwritten by a new message. I don't if this behaviour is intended. Was also mentioned by @bdbogjoe.

![Screenshot 2021-02-24 at 18 26 02](https://user-images.githubusercontent.com/16369502/109040026-c2974980-76cd-11eb-9cd2-1a38340ef711.png)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6037746/zwavejs2mqtt.log)
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6037747/zwavejs_1.log)

**Comment by AlCalzone** [comment] 2021-02-24 19:32
The entire MQTT part is handled by zwavejs2mqtt, so you'll have to talk this through with @robertsLando.

Essentially this value is stateless, so it is not meant to be retained. zwavejs2mqtt resets it to undefined after a second.

**Comment by daballiemo** [comment] 2021-02-24 20:07
> Essentially this value is stateless, so it is not meant to be retained. zwavejs2mqtt resets it to undefined after a second.

I can work with that I think. Thx!

**Comment by robertsLando** [comment] 2021-02-25 07:33
> I now see the scene information in MQTT and I am able to catch it in HA.

**Closed** 2021-02-25 07:33 UTC
Labels: bug
