### ISSUE TITLE
[HASS] Covers do not work in Home Assistant 2021.3.2

### ISSUE THREAD

**Issue by matejdro** [zwave-js/zwavejs2mqtt#830] opened 2021-03-07 05:52 UTC
### Version

Build/Run method

Docker

zwavejs2mqtt version:  2.1.1 
zwavejs version: 6.6.0

### Describe the bug

When attempting to use native Home Assistant MQTT discovery with 2021.3.2, cover position will not be read. Logs are complaining about values not being numeric:

```
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262295,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262345,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262395,"value":4}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 4
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262547,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232039,"value":12}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 12
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232125,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232664,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262295,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 0
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262345,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 0
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262395,"value":4}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 4
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095262547,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 0
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232039,"value":12}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 12
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232125,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 0
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload '{"time":1615095232664,"value":0}' is not numeric
2021-03-07 06:34:28 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 0
```

More info from Home Assistant folks: https://github.com/home-assistant/core/issues/47132#issuecomment-787070899

**Comment by robertsLando** [comment] 2021-03-08 08:45
@billiaz

**Comment by billiaz** [comment] 2021-03-08 10:30
@matejdro can you please post the node export? I am interested on this node! and try to understand what causes it

**Comment by matejdro** [comment] 2021-03-08 10:38
Here you go: 
[shutter_node_export.txt](https://github.com/zwave-js/zwavejs2mqtt/files/6100724/shutter_node_export.txt)

**Comment by darootler** [comment] 2021-03-08 11:12
@billiaz 

Please take a look at my comment [here](https://github.com/home-assistant/core/issues/47342#issuecomment-791947214)

I thinks this has something to do with a recently added breaking change.

Regards
Richard

**Comment by billiaz** [comment] 2021-03-08 12:26
@darootler if devices returns the numbers, numbers should be supported. 

Template supports on pushing the "expected" values to HASS, if something is changed, we probably need to update or change too. 

from the export of node:
```json
  {
        "cover_position": {
            "type": "cover",
            "object_id": "position",
            "discovery_payload": {
                "state_topic": "zwave/Nano_Shutter_Jedilnica/38/0/currentValue",
                "command_topic": "zwave/Nano_Shutter_Jedilnica/38/0/targetValue/set",
                "position_topic": "zwave/Nano_Shutter_Jedilnica/38/0/currentValue",
                "set_position_topic": "zwave/Nano_Shutter_Jedilnica/38/0/targetValue/set",
                "value_template": "{{ value_json.value | round(0) }}",
                "position_open": 99,
                "position_closed": 0,
                "payload_open": 99,
                "payload_close": 0,
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xee0acda9_node64"
                    ],
                    "manufacturer": "Unknown manufacturer 881",
                    "model": "3 (Unknown product 141)",
                    "name": "Nano_Shutter_Jedilnica",
                    "sw_version": "3.4"
                },
                "name": "Nano_Shutter_Jedilnica_position",
                "unique_id": "zwavejs2mqtt_0xee0acda9_64-38-0-currentValue"
            },
            "discoveryTopic": "cover/Nano_Shutter_Jedilnica/position/config",
            "values": [
                "38-0-currentValue",
                "38-0-targetValue"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        }
}
```
as you can see we pash the expected values

and current value:
```
        {
            "id": "64-38-0-currentValue",
            "nodeId": 64,
            "commandClass": 38,
            "commandClassName": "Multilevel Switch",
            "endpoint": 0,
            "property": "currentValue",
            "propertyName": "currentValue",
            "type": "number",
            "readable": true,
            "writeable": false,
            "label": "Current value",
            "stateless": false,
            "min": 0,
            "max": 99,
            "list": false,
            "value": 99,
            "isCurrentValue": true,
            "targetValue": "38-0-targetValue",
            "lastUpdate": 1615180987423,
            "newValue": 99
        },
```

to me it looks like, HASS is not parsing the json value using:

```               
 "value_template": "{{ value_json.value | round(0) }}",
```


but reads the json a whole

**Comment by darootler** [comment] 2021-03-08 12:54
@billiaz 

[Here](https://github.com/home-assistant/core/pull/46059) is the breaking change from HASS. If i understand that correctly the problem is that "state_topic" and "position_topic" is reporting the same numeric value (position of the shutter). HASS is expecting a state like "open, closed, opening, closing or stopped".

A potential fix is explained [here](https://github.com/home-assistant/core/issues/47132#issuecomment-787070899)

I don't know on wich side this has to be fixed, either on zwavejs2mqtt or on the HASS mqtt integration.

Regards
Richard

**Comment by billiaz** [comment] 2021-03-08 20:37
@darootler Thank you for pointing out,
I will post a payload for discovery! if you can add it on your zwavejs2mqtt and check that device, if works! will help me make a patch.

**Comment by billiaz** [comment] 2021-03-08 20:42
@darootler 
I named the device: Cover_test
uniqueid is: 

```json
{
        "cover_position": {
            "type": "cover",
            "object_id": "position",
            "discovery_payload": {
                "command_topic": "zwave/Nano_Shutter_Jedilnica/38/0/targetValue/set",
                "position_topic": "zwave/Nano_Shutter_Jedilnica/38/0/currentValue",
                "set_position_topic": "zwave/Nano_Shutter_Jedilnica/38/0/targetValue/set",
                "position_template": "{{ value_json.value | round(0) }}",
                "position_open": 99,
                "position_closed": 0,
                "payload_open": 99,
                "payload_close": 0,
                "device": {
                    "identifiers": [
                        "zwavejs2mqtt_0xee0acda9_Cover_test"
                    ],
                    "manufacturer": "Unknown manufacturer 881",
                    "model": "3 (Unknown product 141)",
                    "name": "Cover_test",
                    "sw_version": "3.4"
                },
                "name": "Cover_test",
                "unique_id": "zwavejs2mqtt_0xee0acda9_64-38-0-currentValue"
            },
            "discoveryTopic": "cover/Nano_Shutter_Jedilnica/position/config",
            "values": [
                "38-0-currentValue",
                "38-0-targetValue"
            ],
            "persistent": false,
            "ignoreDiscovery": false
        }
}
```

can you try adding this as a new device in your home assistant tab! and then delete it if works

**Comment by darootler** [comment] 2021-03-08 21:08
I am not sure how to add a device with this payload. I am able to publish a packet to topic „homeassistant“, but i am receiving the following error:

'value_json' is undefined

Regards
Richard

**Comment by darootler** [comment] 2021-03-13 21:13
@billiaz 

I was able to "fix" this with [MQTT Explorer](http://mqtt-explorer.com/) and by just removing "state_topic":

![image](https://user-images.githubusercontent.com/11849583/111044486-5ea0af00-8449-11eb-97b4-7adcd7b5b489.png)

Regards
Richard

**Comment by billiaz** [comment] 2021-03-14 10:53
Thank you! I posted a patch!

**Comment by darootler** [comment] 2021-03-14 10:58
Nice, thank you. Did you also replace "value_template" with "position_template?

Regards
Richard

**Comment by billiaz** [comment] 2021-03-14 12:20
@darootler no! pff! just pushed a commit for that!

**Comment by darootler** [comment] 2021-03-14 12:29
Great, thank you!

Regards
Richard

**Comment by darootler** [comment] 2021-03-15 21:17
I just upgraded to version 2.3.0 and the cover topics now look like this one:

```
{
  "state_topic": "zwave/Buro/Buro_Jalousie/38/1/currentValue",
  "command_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "position_topic": "zwave/Buro/Buro_Jalousie/38/1/currentValue",
  "set_position_topic": "zwave/Buro/Buro_Jalousie/38/1/targetValue/set",
  "value_template": "{{ value_json.value | round(0) }}",
  "position_open": 99,
  "position_closed": 0,
  "payload_open": 99,
  "payload_close": 0,
  "position_template": "{{ value_json.value | round(0) }}",
  "device": {
    "identifiers": [
      "zwavejs2mqtt_0xd563c48f_node2"
    ],
    "manufacturer": "Fibargroup",
    "model": "Roller Shutter 3 (FGR223)",
    "name": "Buro-Buro_Jalousie",
    "sw_version": "5.1"
  },
  "name": "Buro-Buro_Jalousie_position_1",
  "unique_id": "zwavejs2mqtt_0xd563c48f_2-38-1-currentValue"
}
```

And i am receiving the following warning:

`2021-03-15 21:32:37 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): 99`

"state_topic" and "value_template" is still there, but "position_template" now seems correct. Is there anything i am missing?

Regards
Richard

**Comment by robertsLando** [comment] 2021-03-16 07:13
I think that the problem is you are receiving `99` as payload but it expectes `open` `closed` etc... Maybe hass has also changed something else with the update?

**Comment by darootler** [comment] 2021-03-16 08:24
If i remove "state_topic" and "value_template" from the payload no more warnings or errors are logged. But for sure both topics will be added again after a while.

Regards
Richard

**Comment by darootler** [comment] 2021-03-16 08:46
I just reviewed "configurations.js" and "devices.js". There are also cover configurations, maybe this also has to updated?

```
  cover_position: {
    type: 'cover',
    object_id: 'position',
    discovery_payload: {
      state_topic: true, # Has this to be removed?
      command_topic: true,
      position_topic: true,
      set_position_topic: true,
      value_template: '{{ value_json.value | round(0) }}', # Has this to be removed?
      position_open: 99,
      position_closed: 0,
      payload_open: '99',
      payload_close: '0'
    }
  },
```

```
const COVER = {
  type: 'cover',
  object_id: 'position',
  values: ['38-0-currentValue', '38-0-targetValue'],
  discovery_payload: {
    command_topic: '38-0-targetValue',
    position_topic: '38-0-currentValue',
    set_position_topic: '38-0-targetValue',
    value_template: '{{ (value_json.value / 99 * 100) | round(0) }}', # Has this to be removed?
    position_open: 99,
    position_closed: 0,
    payload_open: '99',
    payload_close: '0'
  }
}
```

Regards
Richard

**Comment by matejdro** [comment] 2021-03-20 06:57
Can confirm findings from @darootler. Getting same warnings in 2021.3.2.

Covers do seem to work mostly. One thing that does not work is the reported state (it is always "unknown"):

![image](https://user-images.githubusercontent.com/507922/111861866-cd9e6c00-8951-11eb-9ad8-78d5bdda5b9c.png)

However, note that `current_position` on the right is registered fine (which is enough for my use case).

**Comment by darootler** [comment] 2021-03-20 22:45
I am facing the same behavior, covers work (open/close/move slider) but the state is not reported correctly.

Should i open a new issue or should this issue be reopened?

Regards
Richard

**Comment by robertsLando** [comment] 2021-03-22 07:59
@billiaz

**Comment by darootler** [comment] 2021-04-07 17:56
Any updates here? Could someone please reopen this issue since the problem is partially fixed.

Regards
Richard

**Comment by robertsLando** [comment] 2021-04-08 09:05
@billiaz is a bit off in last weeks, I don't follow the mqtt discovery so much as I see many users are switching to the integration so I prefer to focus on UI and control panel improvements

**Comment by darootler** [comment] 2021-04-08 09:33
I am able to "workaround" this problem by editing the discovery topic, but everytime i update Z-Wave JS i have to edit all my topics. Not a huge problem but still annoying, i think there is not much to do to fix this problem.

I just remove "state_topic" and "value_template" from the topics and everything is working as expected.

Regards
Richard

**Comment by Madelaide** [comment] 2021-04-11 10:57
This may help or not, but only recently did my Fibaro blinds start working with position -I needed to trigger a calibration in the configuration page. After that all blinds now set and report position.

**Comment by LooSik** [comment] 2021-05-05 12:01
Any update on this topic? 
My covers are reporting unknown state as well, and it seems like I can't edit the discovery template from the UI either ( I change template, hit update, hit discovery and it posts the non-updated discovery topic according to logs/mqtt )

**Comment by Neonox31** [comment] 2021-06-04 18:40
Same here, unknown state is reported with no possibility to edit discovery template from UI.

**Comment by Neonox31** [comment] 2021-06-05 19:01
Found a workaround today !

- Instead of using UI for discovery template, you should edit directly `nodes.json` file and restart zwavejs2mqtt, the correct template is sent after.
- To fix unknown position, I replaced `value_template` by `position_template` with the same value.

Hope it could help 🤞

**Comment by Lopton** [comment] 2021-06-06 14:09
This affected me after updating HASS last night. Needed to change my value_template with position_template.

**Comment by darootler** [comment] 2021-06-13 12:21
In this [post](https://github.com/zwave-js/zwavejs2mqtt/issues/1327#issuecomment-859728676) someone posted the discovery information and there is no "state_topic". He is using a FGR222 and i am using a FGR223, in my discovery topic there is still a "state_topic". I think this should be removed for FGR 223 too, any news/updates here?

Regards
Richard

**Comment by bushvin** [comment] 2021-06-14 16:20
I have just tested 5.0.2 and it fixed my issue.

**Comment by robertsLando** [comment] 2021-06-15 08:28
@bushvin Another user told me in #1343 that covers are still not working, he suggest to remove state_topic from discovery payload, could it be caused by different hass versions? Maybe he isn't using the latest hass version

**Closed** 2021-06-16 07:09 UTC
