### ISSUE TITLE
[feat] Add a 'stable' docker tag tracking official releases instead of 'latest'

### ISSUE THREAD

**Issue by phipolis** [zwave-js/zwavejs2mqtt#2350] opened 2022-04-04 18:55 UTC
**Is your feature request related to a problem? Please describe.**
In #2349 I experienced a situation where the `latest` tag updated with commits to the master branch, breaking my installation when I pulled the new image. When I went to check if there was a new release, [the last versioned release in github](https://github.com/zwave-js/zwavejs2mqtt/releases) as well as [the last version-tagged docker image](https://hub.docker.com/r/zwavejs/zwavejs2mqtt/tags) was 6.6.2, 10 days previous.

I was confused then about what had changed until I dug into the commit history and saw that `latest` corresponded to a major change  merged into master but not yet tagged and released. The [Zwavejs2mqtt documentation](https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/docker) states docker tags tags include "latest for the latest official release" and "master for the bleeding edge version". Therefore it seems the `latest` tag was changed in error.

**Describe the solution you'd like**
[The consensus seems to be the latest tag is tricky and best avoided](https://vsupalov.com/docker-latest-tag/), and an alternative I've seen (e.g. in projects such as HomeAssistant) is to maintain a separate `stable` tag that tracks the latest official release. That avoids accidental tagging of latest in favor of a custom tag that only gets updated by CI in response to a github release.

**Describe alternatives you've considered**
This may reasonably be considered a bug that `latest` is tracking updates to `master` rather than the latest stable release as advertised. Preventing that would also work. But as the article above mentions, it can be very difficult to always prevent `latest` from getting updated at the wrong time.

**Comment by RichFoley** [comment] 2022-04-04 23:30
Shouldn't only numbered releases get the 'latest' tag? This broke things for me today too.

**Comment by robertsLando** [comment] 2022-04-05 06:35
In latest releases I change the docker meta action that is responsable to create the required tags based on the event that triggers the workflow. I will fix this ASAP to just update latest when there is a new version release

**Comment by robertsLando** [comment] 2022-04-05 06:48
Fixed by https://github.com/zwave-js/zwavejs2mqtt/commit/bcf8f4489460cf0331c4d6ed07c26e90eabc6dd8

**Closed by robertsLando** 2022-04-05 06:48 UTC
Labels: enhancement

**Comment by robertsLando** [comment] 2022-04-05 06:49
I'm really sorry for the issues you are having with latest tag, seems the problem is related to serialport module not working on some archs with docker, follow updates here: https://github.com/zwave-js/zwavejs2mqtt/issues/2349

**Comment by phipolis** [comment] 2022-04-05 17:02
@robertsLando Many thanks for this!
