### ISSUE TITLE
[bug] Unable to view or delete files from store

### ISSUE THREAD

**Issue by macf0x** [zwave-js/zwavejs2mqtt#1042] opened 2021-04-11 13:35 UTC
zwavejs2mqtt: 3.2.0
zwave-js: 7.1.1

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 3.2.0
zwave-js version: 7.1.1

### Describe the bug

Unable to view or delete files from the store.

Log file

```
Error: Not Found
    at /opt/app.js:979:15
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
    at /opt/node_modules/express-session/index.js:502:7
    at readCallback (/opt/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
    at /opt/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
2021-04-11 22:50:48.837 INFO APP: DELETE /api/store//data/store/zwavejs_358.log 404 4.024 ms - 136
Error: Not Found
    at /opt/app.js:979:15
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
    at /opt/node_modules/express-session/index.js:502:7
    at readCallback (/opt/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
    at /opt/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
2021-04-11 22:52:07.298 INFO APP: GET /api/store//data/store/settings.json 404 4.442 ms - 136
Error: Not Found
    at /opt/app.js:979:15
    at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
    at /opt/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/node_modules/express/lib/router/index.js:275:10)
    at /opt/node_modules/express-session/index.js:502:7
    at readCallback (/opt/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
    at /opt/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
2021-04-11 22:52:15.266 INFO APP: GET /api/store//data/store/zwavejs_351.log 404 6.826 ms - 136
```

### To Reproduce

1. Go to Store page
2. Click on on the file
3. Toast error 'Request failed with Error code 404 [Close]'

Similarly, if you click the trash can icon you get the same error.

### Expected behavior

Contents should display in the Right pane.

### Additional context

It is possible to download the logs, if you tick the file and download in.

**Comment by robertsLando** [comment] 2021-04-12 07:19
I think you are running z2m behind a reverse proxy right?

**Comment by macf0x** [comment] 2021-04-12 08:07
Yes I am. Nginx Proxy Manager.

**Comment by robertsLando** [comment] 2021-04-12 08:09
Duplicate of #1013

**Comment by macf0x** [comment] 2021-04-13 17:44
I should note that the issue happens without the reverse proxy.

**Comment by robertsLando** [comment] 2021-04-13 18:41
You said the opposite? Cannot reproduce this on my side

**Comment by robertsLando** [comment] 2021-04-15 07:52
This should be fixed by #1060

**Closed by robertsLando** 2021-04-15 07:52 UTC
Labels: bug

**Comment by macf0x** [comment] 2021-04-15 09:02
@robertsLando Can we reopen as the issue happens directly also.

**Comment by robertsLando** [comment] 2021-04-15 11:39
What you mean? Now it is fixed just wait next release

**Comment by macf0x** [comment] 2021-04-15 12:21
@robertsLando Sorry if I wasn't clear. You asked if I was using a reserve proxy, which is true, but that is only for external access. The issue I'm experiencing is present when using both reverse proxy (external) and going direct to HA.

Unless I'm misunderstanding the fix in that link issue.

I'm happy to retest when the next release drops.
