### ISSUE TITLE
Stuck in loop on getting Command class 44 until it runs out of memory

### ISSUE THREAD

**Issue by elcosmelco** [zwave-js/zwavejs2mqtt#2020] opened 2021-12-03 23:51 UTC
Hi!

On a clean and updated install of **Raspbian Lite** (bullseye) on an **RPi2B** with a freshly installed docker and **ZwaveJS2MQTT** container, as soon as I add a my device and gets to the command classes it floods everything with 100's upon 100's of entries to do with **command class 44** (Scene Actuator Configuration) mostly of ever increasing and repeating `id: '5-44-0-level-41', `and `id: '5-44-0-dimmingDuration-105'` entries (where the last number just goes up and starts over) - right up until it eventually runs out of memory.
Presumably it is displaying the JSON it wants to send over MQTT where I do see :
```
2021-12-03 18:25:43.043 INFO ZWAVE: Node 5: metadata updated: 44-0-dimmingDuration-144
2021-12-03 18:25:43.084 DEBUG MQTT: Publishing to ZwaveBridgeMain/_EVENTS/ZWAVE_GATEWAY-Main/node/node_metadata_updated: {
```
but it is never actually sent. 

While it is doing this the webservice becomes unresponsive and loses connection. The node webservice process at this point is at almost 100% cpu. I can't interact with Zwavejs2Mqtt at all to change any settings, view any logs etc.

The device I've added is a **Aeon Labs ZW075** smart switch and the controller is an Aeotec Gen5 stick.
It previously lived on a Z stick S2 controlled by an openZwave implementation without issues.

I am not using home assistant. and I am on the latest version of ZwaveJS2Mqtt. Due to the issues mentioned I can't get to the logs, except what is scrolling past in ssh.

Any help would be greatly appreciated.

Cheers,
Elco

**Comment by robertsLando** [comment] 2021-12-04 13:28
@elcosmelco could you upload here your settings? Try to set log level to warn both in zwave and general sections in settings

**Comment by elcosmelco** [comment] 2021-12-04 15:15
Ok let me try - I suppose by restarting the docker container and pulling the z stick out before it gets to gathering metadata?
Currently I can't even do that because the endless loop has apparently filled my drive space up so I have to figure out how to clear that first

**Comment by elcosmelco** [comment] 2021-12-04 15:19
Ah I did back up the settings before adding the device
[settings_main.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7654144/settings_main.txt)

**Comment by elcosmelco** [comment] 2021-12-04 16:10
Ok I set the log level as suggested (and also disabled send Zwave Events for now) and it seems to initialize and behave as expected now.
The default log level was set to "silly" by the way. Do you wish to investigate further?

Cheers,
Elco

**Comment by robertsLando** [comment] 2021-12-05 09:25
@elcosmelco IMO the problem is that you have lot of nodes and there are too much logs when log level is set to silly on both driver and application and the process goes out of RAM as your device is limited (1/2GB of RAM I think?).

**Comment by elcosmelco** [comment] 2021-12-05 22:21
That controller only has 1 node added though, but command class 44 is a bit insane where it has it seems 2 properties; `dimming duration` and `level` but each has 255 entries, one for each level value and duration value. This feels wrong as even the web UI barely manages on that CC. I've included a screenshot of the MQTT and web UI - those go on for 255 entries, and again for the other property.

![image](https://user-images.githubusercontent.com/17237681/144766122-bc8c499d-f146-4f13-b471-8fbaf74a4eb8.png)
![image](https://user-images.githubusercontent.com/17237681/144766143-9a321455-6375-4dbc-a4aa-70d025d7a8f6.png)

**Comment by robertsLando** [comment] 2021-12-06 12:53
Humm yeah never seen something like that, I dunno how this could be improved BTW

**Comment by elcosmelco** [comment] 2021-12-06 19:24
Thanx Knipe, good to know!

Then I suppose there is still the question of whether I was stuck in a loop with the log settings at their default, or if it just never finished due to limited resources of the device (a RPi2B ). It went on for minutes though, and I'm pretty sure I saw the same entries multiple times, but I can't be 100% sure at this point.

I'll see if I want to go the custom config file route, though in all honesty, I know just enough docker to get what I need, and if something goes wrong I just nuke the whole thing and load up the config files, so anything that isn't in there will likely not last very long  :smiley:

**Comment by robertsLando** [comment] 2021-12-10 15:27
@elcosmelco If you agree we could close this issue :)

**Comment by elcosmelco** [comment] 2021-12-10 20:51
If you don't think the apparent loop is a bug but more likely the limited resources of the device - we can close

**Closed** 2021-12-10 20:50 UTC
Labels: bug

**Comment by robertsLando** [comment] 2021-12-13 08:18
> If you don't think the apparent loop is a bug but more likely the limited resources of the device - we can close

The loop was due to the fact your server was completely flooded by logs making it impossible to update them correctly :) If you still expect this problem in normal conditions feel free to reopen this issue, thanks :)
