### ISSUE TITLE
[bug] New STORE_DIR env var, causes double slashes in path

### ISSUE THREAD

**Issue by frenck** [zwave-js/zwavejs2mqtt#385] opened 2021-01-29 10:25 UTC
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )
- [x] Home Assistant Add-on

zwavejs2mqtt version: 1.0.0-rc.1
zwavejs version: 6.1.0

### Describe the bug

Set `STORE_DIR` to e.g., `/data/store`

Resulting get requests caused by frontend store feature:

```
2021-01-29 11:37:01.456 INFO APP: GET /api/store//data/store/settings.json 404 1.298 ms - 136 Error: Not Found at /opt/app.js:443:15 at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13) at /opt/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12) at next (/opt/node_modules/express/lib/router/index.js:275:10) at cors (/opt/node_modules/cors/lib/index.js:188:7) at /opt/node_modules/cors/lib/index.js:224:17 at originCallback (/opt/node_modules/cors/lib/index.js:214:15) at /opt/node_modules/cors/lib/index.js:219:13 at optionsCallback (/opt/node_modules/cors/lib/index.js:199:9) at corsMiddleware (/opt/node_modules/cors/lib/index.js:204:7) at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13) at /opt/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
```

Result: `/api/store//data/store/settings.json`

### To Reproduce

See above.

### Expected behavior

Not a 404

### Additional context

Downstream issue: https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/4

Downstream code setting the store path:

https://github.com/hassio-addons/addon-zwavejs2mqtt/blob/265db1f06d1e6e7fb4162242195e3d98038c73df/zwavejs2mqtt/rootfs/etc/services.d/zwavejs2mqtt/run#L10

**Comment by robertsLando** [comment] 2021-01-29 10:35
@frenck Where does that call comes from? It's strange because the url seems malformed. The path provided in the api uses `encodeURIComponent`, but seems that is not correctly parsed.

Ref: https://github.com/zwave-js/zwavejs2mqtt/blob/master/src/apis/ConfigApis.js#L50

Could be it something related to the browser?

**Comment by robertsLando** [comment] 2021-01-29 10:39
Tested and it's working on my side:

```
2021-01-29 11:37:49.478 INFO APP: GET /api/store/%2Fzwavejs2mqtt%2Fstore%2Fdb1da8db.json 304 2.325 ms - -
```

**Comment by frenck** [comment] 2021-01-29 10:47
Interesting, so somewhere along the reverse proxy path it may go south then?

**Comment by robertsLando** [comment] 2021-01-29 10:48
It may, yes.

**Comment by robertsLando** [comment] 2021-01-29 16:41
Sorry closed by error

**Comment by robertsLando** [comment] 2021-02-08 12:54
@frenck Did you fixed this? BTW I can confirm it's not on my side

**Closed** 2021-02-24 14:24 UTC
Labels: bug

**Comment by TheDK** [comment] 2021-03-20 17:00
Just FYI: It is not fixed, workaround is downloading the files.

**Comment by robertsLando** [comment] 2021-03-21 11:01
@TheDK if you install z2m not with the addon it works. I tried to say this to @frenck, it’s not on my side, cannot reproduce it outside the addon
