### ISSUE TITLE
[bug] Aeotec Water Sensor 6 does not discover binary sensors necessary for water detection

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#118] opened 2020-12-29 06:02 UTC
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: 1.2.3

**Describe the bug**
The Aeotec Water Sensor 6 is detected as the correct model and some sensors setup, but the two binary sensors are not discovered by HA for the two water probes (using the dock). This worked correctly in 1.6. 

The two notification classes are detected and sent to mqtt:

When clear (value:0):

```json
{
   "id":"130-113-1-Water Alarm-Sensor status",
   "nodeId":130,
   "commandClass":113,
   "commandClassName":"Notification",
   "endpoint":1,
   "property":"Water Alarm",
   "propertyName":"Water Alarm",
   "propertyKey":"Sensor status",
   "type":"number",
   "readable":true,
   "writeable":false,
   "label":"Sensor status",
   "ccSpecific":{
      "notificationType":5
   },
   "min":0,
   "max":255,
   "list":true,
   "states":[
      {
         "text":"idle",
         "value":0
      },
      {
         "text":"Water leak detected",
         "value":2
      }
   ],
   "value":0,
   "lastUpdate":1609220737810
}
```

When water is detected (value:2):

```json
{
   "id":"130-113-1-Water Alarm-Sensor status",
   "nodeId":130,
   "commandClass":113,
   "commandClassName":"Notification",
   "endpoint":1,
   "property":"Water Alarm",
   "propertyName":"Water Alarm",
   "propertyKey":"Sensor status",
   "type":"number",
   "readable":true,
   "writeable":false,
   "label":"Sensor status",
   "ccSpecific":{
      "notificationType":5
   },
   "min":0,
   "max":255,
   "list":true,
   "states":[
      {
         "text":"idle",
         "value":0
      },
      {
         "text":"Water leak detected",
         "value":2
      }
   ],
   "value":2,
   "lastUpdate":1609220736395
}
```

But binary sensors are not created:

![image](https://user-images.githubusercontent.com/33612110/103261954-646e1480-4971-11eb-8abd-f2369fd17cce.png)

Here is the ozw 1.6 device file: https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw122.xml

I have several of these and they are all the same.

**To Reproduce**
1. Pair sensor

**Expected behavior**
Two binary_sensors should be created reflecting the notification command class.

**Additional context**

Here is the log file during a trip of one of the water sensors:

```
05:45:36.112 DRIVER « [Node 130] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 1
                        └─[NotificationCCReport]
                            notification type:   Water Alarm
                            notification status: 255
                            notification state:  Water leak detected
05:45:36.117 CNTRLR   [Node 130] [+] [Notification] Water Alarm[Sensor status]: 2       [Endpoint 1]
05:45:36.330 SERIAL « 0x0114000400820e600d01017105000000ff0502000082                      (22 bytes)
05:45:36.331 SERIAL » [ACK]                                                                   (0x06)
05:45:36.332 DRIVER « [Node 130] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 1
                        └─[NotificationCCReport]
                            notification type:   Water Alarm
                            notification status: 255
                            notification state:  Water leak detected
05:45:36.334 CNTRLR   [Node 130] [~] [Notification] Water Alarm[Sensor status]: 2 => 2  [Endpoint 1]
05:45:36.390 SERIAL « 0x0114000400820e600d01007105000000ff0502000083                      (22 bytes)
05:45:36.391 SERIAL » [ACK]                                                                   (0x06)
05:45:36.393 DRIVER « [Node 130] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 0
                        └─[NotificationCCReport]
                            notification type:   Water Alarm
                            notification status: 255
                            notification state:  Water leak detected
05:45:36.394 CNTRLR   [Node 130] [~] [Notification] Water Alarm[Sensor status]: 2 => 2  [Endpoint 1]
05:45:37.739 SERIAL « 0x0114000400820e600d01017105000000ff0500000080                      (22 bytes)
05:45:37.741 SERIAL » [ACK]                                                                   (0x06)
05:45:37.743 DRIVER « [Node 130] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 1
                        └─[NotificationCCReport]
                            notification type:   Water Alarm
                            notification status: 255
                            notification event:  Unknown (0x00)
05:45:37.809 CNTRLR   [Node 130] [~] [Notification] Water Alarm[Sensor status]: 2 => 0  [Endpoint 1]
05:45:37.823 SERIAL « 0x0114000400820e600d01007105000000ff0500000081                      (22 bytes)
05:45:37.824 SERIAL » [ACK]                                                                   (0x06)
05:45:37.828 DRIVER « [Node 130] [REQ] [ApplicationCommand]
                      └─[MultiChannelCCCommandEncapsulation]
                        │ source:      1
                        │ destination: 0
                        └─[NotificationCCReport]
                            notification type:   Water Alarm
                            notification status: 255
                            notification event:  Unknown (0x00)

```

**Comment by blhoward2** [comment] 2020-12-29 06:18
There are two sensors detected upon further investigation, and they correctly respond to water detection, but there should also be binary sensors created for consistency with other water sensors (as my others (Aeotec DSB45s) setup binary sensors even with zwavejs2mqtt). Having binary sensors also makes automations much easier.

**Comment by robertsLando** [comment] 2020-12-29 07:17
@blhoward2 What docker tag are you using? `latest` ? If so try first to use the `dev` tag

**Comment by blhoward2** [comment] 2020-12-29 07:19
> @blhoward2 What docker tag are you using? `latest` ? If so try first to use the `dev` tag

I built one off a clone I made this afternoon (using the command on the docker page). That should be at least as fresh as dev, no?

**Comment by robertsLando** [comment] 2020-12-29 07:22
> That should be at least as fresh as dev, no

Nope. `dev` is builded on every commit on master, `latest` is builded on every release.

**Comment by blhoward2** [comment] 2020-12-29 07:25
> > That should be at least as fresh as dev, no
> 
> Nope. `dev` is builded on every commit on master, `latest` is builded on every release.

Got it. I’ll try that this weekend and then update all of the bugs I’ve filed.

**Comment by robertsLando** [comment] 2020-12-29 07:27
@blhoward2 I think that also other issues you have found may be resolved with that

**Comment by blhoward2** [comment] 2021-01-03 03:30
I can confirm that this issue persists on the most recent dev image, pulled today. The only binary sensor created is for the battery level. There should be two binary sensors created as this sensor has two probes.

![Screen Shot 2021-01-02 at 10 30 19 PM](https://user-images.githubusercontent.com/33612110/103471132-1f1f5d80-4d4a-11eb-8281-9cbb6e82b132.png)

**Comment by robertsLando** [comment] 2021-01-04 16:09
@billiaz COuld you take a look at this?

**Comment by billiaz** [comment] 2021-01-05 19:00
What we see in these logs is, a multi level sensor (notification report) which has different values. the sensor can support any possible value exposed by the device.

usually 0 = idle and 1-255 is a value. this works as intended. Water sensor 6 reports notification sensors and not binary sensors as I can see @blhoward2 do you also have binary sensors discovered? can you see these on your ui?

**Comment by blhoward2** [comment] 2021-01-05 19:06
In ozw 1.4 and 1.6 binary sensors are discovered that report on/off for water detected or not. This fits nicely with HA’s binary sensor platform for water, which makes it water detected or not, and simplifies automations. It is also consistent with other water sensors. Whether the device reports it or ozw simply changes the values based on whether it is receiving 0 or not, I don’t know. I can investigate more later tonight. A range of 1-255 makes little sense for water detection sensor as it is either on or off. 

FWIW, when I tested this the only sensors I saw updating in HA with water detection changed from the text “idle” to “water leak detected.” This seems to simply be a backend choice to present it in this manner as it is really reporting 0 or 2 and using a value template to present text versus a binary sensor according to the sensor definition in the UI.

**Comment by billiaz** [comment] 2021-01-05 19:10
ozw 1.4 and 1.6 does a lot of changes on how sensors translated from notificationreports to binary sensors. On the other hand other devices like zipato, do show the notification report label.
we till now have implemented the direct translation and a bit of labeling based on the Driver labels exposed.

It is easy to setup a custom device to also generate binary sensor on HASS. as probably will show it in a different way.

@robertsLando do you think is good to expose these different types as binary sensors instead of sensor? we will need to find only devices with 2 possible values, but might take some time.

**Comment by blhoward2** [comment] 2021-01-05 19:12
I’m not the expert, but if you look at whatever is feeding the sensor I quoted above that only seems to present 0 or 2 according to the value template.

**Comment by blhoward2** [comment] 2021-01-05 19:13
Couldn’t you define one in the same was the sensor above, but instead of the text make it report on/off?

**Comment by billiaz** [comment] 2021-01-05 19:16
> In ozw 1.4 and 1.6 binary sensors are discovered that report on/off for water detected or not. This fits nicely with HA’s binary sensor platform for water, which makes it water detected or not, and simplifies automations. It is also consistent with other water sensors. Whether the device reports it or ozw simply changes the values based on whether it is receiving 0 or not, I don’t know. I can investigate more later tonight. A range of 1-255 makes little sense for water detection sensor as it is either on or off. Are you sure you are looking at the water detection and not one of the many other values like temp, tilt, etc. that it provides?
> 
> FWIW, when I tested this the only sensors I saw updating in HA with water detection changed from the text “idle” to “water leak detected.” This seems to simply be a choice (by node-zwave-js or zwavejs2mqtt I don’t know) to present it in this manner as it is really reporting 0 or 2 and using a value template to present text versus a binary sensor according to the sensor definition in the UI. (This is in the sensor definition I included above.) I’m aware of no other water sensor on any platform that presents the notification in a text-based manner like this, and my other water sensors do not under zwavejs2mqtt.

I understand the confusion, most of these are implemented as in specification. there is a list of possible values on each propertyKey on notificationreports, which makes it a long list to support, and programmatically probably a bit confusing.

an example from the excel: https://www.silabs.com/documents/login/miscellaneous/SDS13713-Notification-Command-Class.xlsx

![CC notification example](https://user-images.githubusercontent.com/4048920/103688805-afe87a00-4f92-11eb-875c-25cbb2ba170f.jpg)


Some are states, some are events. It is getting confusing the more we read this list.

What I want to say this specific device exposes only 0 and 2, but others do expose multiple values and subvalues!
the missing native Home assistant connection does not also make it easy to create some "special" entity which will have states and different icons.
The commont part on these is idle is always the default state on a notification type

**Comment by billiaz** [comment] 2021-01-05 19:19
> Couldn’t you define one in the same way as the sensor above, but instead of the text make it report a binary state? It may technically support a range but it only seems to ever generate 0 (dry) or 255 (wet). The log above is when I was tripping the water sensor.

i understand what you mean! that was my first thought, a binary (on/off) state. reading the spec more and more becomes complicated.

the more devices move to multilevel notification reports, the more we will see this changing from on/off states to 
off/leak/low level/hot water etc...

**Comment by blhoward2** [comment] 2021-01-05 19:19
Even still from an automation perspective, all of those would benefit from a binary in idle/alert status just to trip an alarm. Then you’d have the sensor indicating the exact message.

**Comment by billiaz** [comment] 2021-01-05 19:20
> Even still from an automation perspective, all of those would benefit from a binary in idle/alert status just to trip an alarm. Then you’d have the sensor indicating the exact message.

for automation, i use also nodered! as it posts to my telegraf and is fast. you could always test the state if is 0 or false (value_json.value) is always numeric. or report.

I do not know how difficult is to report if sensor is not Idle (0) as an alarming state

**Comment by blhoward2** [comment] 2021-01-05 19:24
Bah, Appdaemon all the way. In any event, maybe expose both a sensor and binary_sensor and let the user hide one if they want? What is most annoying is that automating off water sensors means that some need to be on/off, some tested against text. As many people use a group to ease automation, that means two automations or manually defining a binary sensor in HA and then using that.

**Comment by billiaz** [comment] 2021-01-05 19:27
I get it. i would personally overcome this with: if value != "0" || value != false - alarm
i am not fun of appdaemon :) but is personal preference.

it is easy to generate a binary sensor for devices. using customDevice.json. you can (before we get a reply from @robertsLando 's opinion) a binary_sensor discovery for all devices of same model

**Comment by blhoward2** [comment] 2021-01-05 19:29
Yes, I know that I can personally override this. I’m on a mission of trying to make as many things work out-of-the-box in a similar way (where it makes sense) to ease transitions and reduce tech support type issues. As it is done this way now, telling people that switch to redo all of their automations is just more work.

**Comment by gdt** [comment] 2021-01-05 19:43
A perspective from outside; I have used echolink flood sensors under the old integration.   I found that they support binary sensors natively in zwave, which is somehow an older scheme.  They also support sensors with values that are 2 for flood, maybe 8 for not, and 3 for tamper, 8 for not.  These are apparently the newer zwave way.   So I create a template sensor to make  a binary sensor for this.  It sounds like this is what's going on here.   The suggestion to encode in zwavejs2mqtt the mapping of these multi-valued sensors into binary sensors makes sense as a plan to show mqtt a higher-level representation.

**Comment by robertsLando** [comment] 2021-01-22 10:14
@blhoward2 Is this fixed?

**Comment by blhoward2** [comment] 2021-01-22 15:00
I don’t believe so. I’ll check later.

**Comment by robertsLando** [comment] 2021-01-23 09:51
LMK

**Comment by blhoward2** [comment] 2021-01-24 07:18
@robertsLando Confirmed that this is still an issue. No binary sensor is setup, just a text sensor.

[node_122.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5861699/node_122.json.zip)

**Comment by robertsLando** [comment] 2021-01-26 13:55
> Confirmed that this is still an issue. No binary sensor is setup, just a text sensor.

I ned to know the specific valueIds you expect to see as a sensor in hass

**Comment by blhoward2** [comment] 2021-01-26 14:37
It’s the one above, isn’t it? It’s just that we’re templating the status into different templates. I get why but I think we should also have a binary sensor for status that reflects 0 or 255 to show it is in an alarm state.

**Comment by billiaz** [comment] 2021-01-26 15:58
@blhoward2 this is not a bug. Aeotec has only the Multilevel Notification. I think we can move this into a discussion
And find a good solution how to represent the Notification Command Class in Home assistant.
@robertsLando what you think?

**Comment by blhoward2** [comment] 2021-01-26 16:00
I realize now that it isn’t a big per se, it’s more of a feature request.

**Comment by robertsLando** [comment] 2021-01-26 16:03
>  I think we can move this into a discussion And find a good solution how to represent the Notification Command Class in Home assistant.

Ok go for it :)

**Closed** 2021-02-01 14:39 UTC
Labels: bug
