### ISSUE TITLE
[bug] UI doesn't show some states in lists values

### ISSUE THREAD

**Issue by jghaanstra** [zwave-js/zwavejs2mqtt#101] opened 2020-12-21 08:22 UTC
**Is your feature request related to a problem? Please describe.**
Greenwave sockets have an annoying feature where the LED on the socket starts blinking after a configurable time of inactivity. The highest value you can set this to is however 255 minutes (setting 112-0-1). For sockets that are not used that much or for instance at night this blinking occurs after this time. To avoid the LED from blinking communication between the controller is needed. On zwave2mqtt there was a user setting that you could set to "Disable" for instance every 4 hours to make sure the blinking does not occur. The setting didnt do anything else, it would automatically update to enable again so you could just send disable every 4 hours and that would avoid the LED for starting to blink. The setting in zwave2mqtt was 112-1-4.

I do see a setting under config within zwavejs2mqtt called LED for network error (122-0-4) which seems to be the same setting. Setting this from the UI however does not stop the light from blinking. It looks like it's not actually being saved and I'm not seeying anything being published to MQTT either. And I dont know how to set this setting through MQTT. On zwave2mqtt I published a payload `"Disable"` to 112-1-4-set every 4 hours but publish this to 112-0-4-targetValue-set doesnt work. So i'd appreciate if this could be fixed somehow so my LEDs dont start blinking at night. Below are the ID's of the Greenwave products I'm talking about.

* Single socket: 153-2-2 (0x0099-0x0002-0x0002)
* multi socket brick: 153-4-3 (0x0099-0x0004-0x0003)

**Comment by robertsLando** [comment] 2020-12-21 10:38
@kpine Also reports some strange behaviour on ui with thermostat operating state

**Comment by jghaanstra** [comment] 2020-12-21 10:42
It's not just the UI I think. It looks to update the value when I edit the setting in the UI but on reloading the page this config value is empty again. This setting is also not published on the MQTT server.

![image](https://user-images.githubusercontent.com/4710062/102768500-91bf2f00-4381-11eb-9f4b-90b76a98352c.png)

**Comment by robertsLando** [comment] 2020-12-21 10:46
@j9brown Do you press the send button when you change it from the select?

**Comment by jghaanstra** [comment] 2020-12-21 10:53
I assume you wanted to mention me. Yes, I did press the send button. Tried multiple times.

**Comment by robertsLando** [comment] 2020-12-21 10:54
I think I know what's going on, let me try to submit a fix for this

**Comment by jghaanstra** [comment] 2020-12-21 10:56
There is actually another setting right next to it for the power on state (112-0-3) which shows the same behaviour. Also a select list that does not seem to do anything. If the fix is generic this will be fixed as well, if not you might need to look into that as well.

**Comment by robertsLando** [comment] 2020-12-21 12:43
The strange thing here is that those values doesn't have a  `value` and `newValue` props

**Comment by robertsLando** [comment] 2020-12-21 12:50
@jghaanstra @kpine could you give a try to #102?

**Comment by jghaanstra** [comment] 2020-12-21 12:53
I'm running a Docker container. Not sure how to test a single commit.

I just noticed something else. The controller status is reporting `Driver: Configuration: "4" must be of type "number", received "string"` after trying to update one of the mentioned settings. It seems it's trying to save the string from the list. Is that what you fixed with the latest commit?

**Comment by robertsLando** [comment] 2020-12-21 14:26
@jghaanstra could you show me the z2m output? it should output something like `unable to write value xx to yyy`

**Comment by jghaanstra** [comment] 2020-12-21 14:32
I made a video showing what is going on.


https://user-images.githubusercontent.com/4710062/102787674-bb884e00-43a1-11eb-9aec-2348671ff3eb.mp4

**Comment by robertsLando** [comment] 2020-12-21 14:41
@jghaanstra thanks for the video, now it's more clear! firstly I thought that you didn't see the option but now I see that the options are there but the problem is that the write request fails for some reason. Anyway you will never see the log in this way as the log only works while the debig tab is active. YOu should check logs using docker logs command

**Comment by jghaanstra** [comment] 2020-12-21 14:45
Ok, that's good to know. If I have two tabs open I see some logging when editing one the mentioned configuration values. This is waht is says:

```
2020-12-21 15:44:20.065 INFO SOCKET: Event ZWAVE_API emitted to Q2va-PlX6lGy-2ivAAAh
2020-12-21 15:44:20.067 INFO APP: Zwave api call: writeValue [object Object],1
2020-12-21 15:44:20.137 INFO ZWAVE: Success zwave api call writeValue
```

**Comment by aretakisv** [comment] 2020-12-21 14:55
@jghaanstra can you enable log to file! set it to silly and restart your container?
then under bin/zwave-1.log (1 stands for the PID of your node) you will see the logs of the Driver.

Once everything settles try to tail the log and send the same command, then paste here the logs!

We will see what driver replies

**Comment by jghaanstra** [comment] 2020-12-21 15:19
Here you go.

```
16:17:33.496 SERIAL » 0x010c00130b057004040100257cc6                                      (14 bytes)
16:17:33.496 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      124
                      └─[ConfigurationCCSet]
                          parameter #:      4
                          reset to default: false
                          value size:       1
                          value:            0
16:17:33.498 SERIAL « [ACK]                                                                   (0x06)
16:17:33.505 SERIAL « 0x0104011301e8                                                       (6 bytes)
16:17:33.505 SERIAL » [ACK]                                                                   (0x06)
16:17:33.506 DRIVER « [RES] [SendData]
                        was sent: true
16:17:33.547 SERIAL « 0x011800137c00000501c47f7f7f7f000003080000000301000041              (26 bytes)
16:17:33.550 SERIAL » [ACK]                                                                   (0x06)
16:17:33.551 DRIVER « [REQ] [SendData]
                        callback id:     124
                        transmit status: OK
16:17:33.559 SERIAL » 0x010a00130b03700504257dc7                                          (12 bytes)
16:17:33.560 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      125
                      └─[ConfigurationCCGet]
                          parameter #: 4
16:17:33.563 SERIAL « [ACK]                                                                   (0x06)
16:17:33.568 SERIAL « 0x0104011301e8                                                       (6 bytes)
16:17:33.569 SERIAL » [ACK]                                                                   (0x06)
16:17:33.573 DRIVER « [RES] [SendData]
                        was sent: true
16:17:33.619 SERIAL « 0x011800137d00000501c47f7f7f7f000003080000000301000040              (26 bytes)
16:17:33.619 SERIAL » [ACK]                                                                   (0x06)
16:17:33.620 DRIVER « [REQ] [SendData]
                        callback id:     125
                        transmit status: OK
16:17:35.228 CNTRLR   [Node 011] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
16:17:35.232 SERIAL « 0x011100040003097105000000ff070800b300d7                            (19 bytes)
16:17:35.233 SERIAL » [ACK]                                                                   (0x06)
16:17:35.234 DRIVER « [Node 003] [REQ] [ApplicationCommand]
                      └─[NotificationCCReport]
                          notification type:   Home Security
                          notification status: 255
                          notification state:  Motion detection
16:17:35.236 CNTRLR   [Node 003] [~] [Notification] Home Security[Motion sensor status] [Endpoint 0]
                      : 0 => 8
16:17:35.408 SERIAL « 0x010c00040003043003ff0cb50085                                      (14 bytes)
16:17:35.409 CNTRLR   [Node 003] [Binary Sensor] Motion: metadata updated               [Endpoint 0]
16:17:35.411 CNTRLR   [Node 003] [~] [Binary Sensor] Motion: false => true              [Endpoint 0]
16:17:35.412 SERIAL » [ACK]                                                                   (0x06)
16:17:35.415 DRIVER « [Node 003] [REQ] [ApplicationCommand]
                      └─[BinarySensorCCReport]
                          type:  Motion
                          value: true
16:17:35.738 SERIAL » 0x010a00130b03700504257dc7                                          (12 bytes)
16:17:35.738 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      125
                      └─[ConfigurationCCGet]
                          parameter #: 4
16:17:35.741 SERIAL « [ACK]                                                                   (0x06)
16:17:35.747 SERIAL « 0x0104011301e8                                                       (6 bytes)
16:17:35.747 SERIAL » [ACK]                                                                   (0x06)
16:17:35.748 DRIVER « [RES] [SendData]
                        was sent: true
16:17:35.789 SERIAL « 0x011800137d00000401c47f7f7f7f000003080000000301000041              (26 bytes)
16:17:35.790 SERIAL » [ACK]                                                                   (0x06)
16:17:35.790 DRIVER « [REQ] [SendData]
                        callback id:     125
                        transmit status: OK
16:17:37.028 SERIAL « 0x011100040019097105000000ff070800b800c6                            (19 bytes)
16:17:37.029 SERIAL » [ACK]                                                                   (0x06)
16:17:37.030 DRIVER « [Node 025] [REQ] [ApplicationCommand]
                      └─[NotificationCCReport]
                          notification type:   Home Security
                          notification status: 255
                          notification state:  Motion detection
16:17:37.037 CNTRLR   [Node 025] [~] [Notification] Home Security[Motion sensor status] [Endpoint 0]
                      : 8 => 8
16:17:37.050 SERIAL « 0x010c00040019043003ff0cb80092                                      (14 bytes)
16:17:37.051 CNTRLR   [Node 025] [Binary Sensor] Motion: metadata updated               [Endpoint 0]
16:17:37.053 CNTRLR   [Node 025] [~] [Binary Sensor] Motion: true => true               [Endpoint 0]
16:17:37.054 SERIAL » [ACK]                                                                   (0x06)
16:17:37.056 DRIVER « [Node 025] [REQ] [ApplicationCommand]
                      └─[BinarySensorCCReport]
                          type:  Motion
                          value: true
16:17:37.395 CNTRLR   [Node 011] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
16:17:37.899 SERIAL » 0x010a00130b03700504257dc7                                          (12 bytes)
16:17:37.900 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      125
                      └─[ConfigurationCCGet]
                          parameter #: 4
16:17:37.902 SERIAL « [ACK]                                                                   (0x06)
16:17:37.908 SERIAL « 0x0104011301e8                                                       (6 bytes)
16:17:37.908 SERIAL » [ACK]                                                                   (0x06)
16:17:37.909 DRIVER « [RES] [SendData]
                        was sent: true
16:17:37.950 SERIAL « 0x011800137d00000401c47f7f7f7f000003080000000301000041              (26 bytes)
16:17:37.951 SERIAL » [ACK]                                                                   (0x06)
16:17:37.951 DRIVER « [REQ] [SendData]
                        callback id:     125
                        transmit status: OK
```

**Comment by AlCalzone** [comment] 2020-12-21 15:24
That looks like the set command goes through, but the followup get to verify the change doesn't work.

**Comment by AlCalzone** [comment] 2020-12-21 15:32
Just tested again with my device (without the zjs2mqtt though) and the get request gets a response 🤷🏻‍♂️

**Comment by robertsLando** [comment] 2020-12-21 15:33
@AlCalzone Do you think it's something caused by z2m? could you give it a try?

**Comment by AlCalzone** [comment] 2020-12-21 15:35
let me try

**Comment by AlCalzone** [comment] 2020-12-21 15:45
Works like a charm 🤷🏻‍♂️

**Comment by jghaanstra** [comment] 2020-12-21 16:00
Ok, that's weird. What version of zwavejs2mqtt are you using and how does it look like on the MQTT server?

**Comment by AlCalzone** [comment] 2020-12-21 16:30
I compiled and ran the version from github master. I normally don't use mqtt or the dashboard, what do you mean with
> how does it look like on the MQTT server

**Comment by jghaanstra** [comment] 2020-12-21 16:37
Do you see the configured values of these setting on a connected MQTT server? Because I'm not seeying anything there. The configuration values are missing completely.

![image](https://user-images.githubusercontent.com/4710062/102799663-1eceac00-43b3-11eb-89e0-d969bb33b9c7.png)

**Comment by AlCalzone** [comment] 2020-12-21 22:35
Hmm that's all I see there:
![grafik](https://user-images.githubusercontent.com/17641229/102828493-2dce5200-43e5-11eb-82af-07169059fa48.png)

**Comment by kpine** [comment] 2020-12-22 07:00
Here's what the UI looks like for my thermostat:
![image](https://user-images.githubusercontent.com/791794/102858086-851cf400-43de-11eb-8596-9c837c6b4c46.png)

Note I am just observing how the values are displayed, I'm not trying to set anything. The Operating state shows 0 but I would expect "Idle". It is a list, according to the MQTT data I posted in #92. Similarly, the mode value is a list, currently set to value 0 which is "Off", but it is shown as expected.

Finally, here is a debug log snippet, it seems to recognize it as Idle.
```
08:17:55.038 CNTRLR » [Node 005] querying thermostat operating state...
08:17:55.041 SERIAL » 0x01090013050242022530b7                                            (11 bytes)
08:17:55.041 DRIVER » [Node 005] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      48
                      └─[ThermostatOperatingStateCCGet]
08:17:55.044 SERIAL « [ACK]                                                                   (0x06)
08:17:55.052 SERIAL « 0x0104011301e8                                                       (6 bytes)
08:17:55.053 SERIAL » [ACK]                                                                   (0x06)
08:17:55.053 DRIVER « [RES] [SendData]
                        was sent: true
08:17:55.077 SERIAL « 0x011800133000000300ca7f7f7f7f01010300000000020100000d              (26 bytes)
08:17:55.077 SERIAL » [ACK]                                                                   (0x06)
08:17:55.079 DRIVER « [REQ] [SendData]
                        callback id:     48
                        transmit status: OK
08:17:55.171 SERIAL « 0x010b0004000503420300ca007d                                        (13 bytes)
08:17:55.171 CNTRLR   [Node 005] [~] [Thermostat Operating State] state: 0 => 0         [Endpoint 0]
08:17:55.171 SERIAL » [ACK]                                                                   (0x06)
08:17:55.172 DRIVER « [Node 005] [REQ] [ApplicationCommand]
                      └─[ThermostatOperatingStateCCReport]
                          state: Idle
08:17:55.173 CNTRLR « [Node 005] received current thermostat operating state: Idle
08:17:55.182 CNTRLR   [Node 005] [~] [Thermostat Operating State] interviewC [Endpoint 0] [internal]
                      omplete: true => true
```

**Comment by robertsLando** [comment] 2020-12-22 07:48
Ooh got it, operating state is read only, that’s why you see a number. It’s an easy fix so 

---

Daniel

**Comment by robertsLando** [comment] 2020-12-22 13:34
@jghaanstra Check master :)

**Closed** 2020-12-22 13:34 UTC

**Comment by jghaanstra** [comment] 2020-12-22 13:36
Thanx, I''m running a Docker container though and need to wait till `dev` or `latest` has been updated.

**Comment by robertsLando** [comment] 2020-12-22 13:38
`dev` will be updated once this is completed: https://github.com/zwave-js/zwavejs2mqtt/runs/1595051810

**Comment by jghaanstra** [comment] 2020-12-22 21:26
I updated to latest `dev` but my issue is not resolved unfortunately. What can I do?

**Comment by jghaanstra** [comment] 2020-12-22 21:48
And here is the log from the file.

```
22:45:41.093 SERIAL » 0x010c00130b0570040401002560da                                      (14 bytes)
22:45:41.095 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      96
                      └─[ConfigurationCCSet]
                          parameter #:      4
                          reset to default: false
                          value size:       1
                          value:            0
22:45:41.098 SERIAL « [ACK]                                                                   (0x06)
22:45:41.103 SERIAL « 0x0104011301e8                                                       (6 bytes)
22:45:41.104 SERIAL » [ACK]                                                                   (0x06)
22:45:41.105 DRIVER « [RES] [SendData]
                        was sent: true
22:45:41.146 SERIAL « 0x011800136000000401c37f7f7f7f00000308000000030100005b              (26 bytes)
22:45:41.147 SERIAL » [ACK]                                                                   (0x06)
22:45:41.148 DRIVER « [REQ] [SendData]
                        callback id:     96
                        transmit status: OK
22:45:41.161 SERIAL » 0x010a00130b037005042561db                                          (12 bytes)
22:45:41.162 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      97
                      └─[ConfigurationCCGet]
                          parameter #: 4
22:45:41.166 SERIAL « [ACK]                                                                   (0x06)
22:45:41.170 SERIAL « 0x0104011301e8                                                       (6 bytes)
22:45:41.170 SERIAL » [ACK]                                                                   (0x06)
22:45:41.171 DRIVER « [RES] [SendData]
                        was sent: true
22:45:41.213 SERIAL « 0x011800136100000401c17f7f7f7f000003080000000301000058              (26 bytes)
22:45:41.214 SERIAL » [ACK]                                                                   (0x06)
22:45:41.215 DRIVER « [REQ] [SendData]
                        callback id:     97
                        transmit status: OK
22:45:42.820 CNTRLR   [Node 011] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
22:45:43.330 SERIAL » 0x010a00130b037005042561db                                          (12 bytes)
22:45:43.331 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      97
                      └─[ConfigurationCCGet]
                          parameter #: 4
22:45:43.334 SERIAL « [ACK]                                                                   (0x06)
22:45:43.340 SERIAL « 0x0104011301e8                                                       (6 bytes)
22:45:43.344 SERIAL » [ACK]                                                                   (0x06)
22:45:43.345 DRIVER « [RES] [SendData]
                        was sent: true
22:45:43.383 SERIAL « 0x011800136100000401c37f7f7f7f00000308000000030100005a              (26 bytes)
22:45:43.383 SERIAL » [ACK]                                                                   (0x06)
22:45:43.384 DRIVER « [REQ] [SendData]
                        callback id:     97
                        transmit status: OK
22:45:44.989 CNTRLR   [Node 011] did not respond after 2/3 attempts. Scheduling next try in 500 ms.
22:45:45.493 SERIAL » 0x010a00130b037005042561db                                          (12 bytes)
22:45:45.494 DRIVER » [Node 011] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      97
                      └─[ConfigurationCCGet]
                          parameter #: 4
22:45:45.496 SERIAL « [ACK]                                                                   (0x06)
22:45:45.502 SERIAL « 0x0104011301e8                                                       (6 bytes)
22:45:45.503 SERIAL » [ACK]                                                                   (0x06)
22:45:45.504 DRIVER « [RES] [SendData]
                        was sent: true
22:45:45.544 SERIAL « 0x011800136100000401c17f7f7f7f000003080000000301000058              (26 bytes)
22:45:45.545 SERIAL » [ACK]                                                                   (0x06)
22:45:45.546 DRIVER « [REQ] [SendData]
                        callback id:     97
                        transmit status: OK
```

**Comment by robertsLando** [comment] 2020-12-23 07:23
> On the MQTT server there is no property 112-0-4. Perhaps that's why it says undefined.

Nope is the log that is showing undefined because the value sent there hasn't a property `id`. Now I have submitted a fix to show the correct id there. 

Based on your logs seems the command isn't received but it's sent correctly, @AlCalzone device issue?

**Comment by jghaanstra** [comment] 2020-12-23 07:40
I have multiple Greenwave devices that behave the same way and which are working fine on zwave2mqtt (including this setting that allows me avoid the blinking of the LED). That does not indicate a device issue. What would be the correct topic for updating this config value through MQTT, perhaps that works?!?

**Comment by robertsLando** [comment] 2020-12-23 07:59
> What would be the correct topic for updating this config value through MQTT

It depends on your gateway configuration, do you have mqtt explorer? If so just find the topic where that configuration is published, add `/set` to the end and publish the value you want to set. Anyway I don't say it's your device bugged but maybe it needs a compatibility flag or something else in order to make this working, your previous logs seems truncated, could you send a full log of a write try? also remeber to set log level to verbose

**Comment by AlCalzone** [comment] 2020-12-23 08:38
> I have multiple Greenwave devices that behave the same way and which are working fine on zwave2mqtt (including this setting that allows me avoid the blinking of the LED)

Can you show me a log of that please? Looking at the log above it seems like the set command is acknowledged, but verifying the change fails because the device doesn't answer for some reason.

Also: which firmware versions do your devices have? Mine is on 4.28.

**Comment by jghaanstra** [comment] 2020-12-23 10:23
> It depends on your gateway configuration, do you have mqtt explorer? If so just find the topic where that configuration is published, add `/set` to the end and publish the value you want to set.
When I try to set it with `zwave/logeerkamer/crosstrainer/112/0/4/set` the result is:
![image](https://user-images.githubusercontent.com/4710062/102983445-60269f00-450c-11eb-9f8f-6a42de634e32.png)


As you can see there are also two setting topics under `zwave/logeerkamer/crosstrainer/112/0/` and `zwave/logeerkamer/crosstrainer/112/ /` . Especially this last one seems strange to me with an empty value in the path. But using the set command does not work. I can update the topics directly with `zwave/logeerkamer/crosstrainer/112/0/4` and `zwave/logeerkamer/crosstrainer/112//4` and set it to 0 or 1 and this looks good on the MQTT server but does not seem to have any effect in the UI.


> logs seems truncated, could you send a full log of a write try? also remeber to set log level to verbose
It wasnt truncated but communication seems to stop after attempt 2 out of 3. There is no third attempt. But here is a full log. At 11:15:31.220 I try to update node006 with this setting and at 11:17:39.500 I try to update node011.

[zwave-1.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5734602/zwave-1.zip)


> Can you show me a log of that please? Looking at the log above it seems like the set command is acknowledged, but verifying the change fails because the device doesn't answer for some reason.
It's not that easy as the MQTT structure has changed in zwavejs2mqtt. I'll see if I can find some time during the holidays.


> Also: which firmware versions do your devices have? Mine is on 4.28.
I'm on 4.21 for all my Greenwave devices.

**Comment by robertsLando** [comment] 2020-12-23 10:27
@jghaanstra What's the payload type you choosed in settings? Json time-value, raw value, valueId?

**Comment by jghaanstra** [comment] 2020-12-23 10:33
> @jghaanstra What's the payload type you choosed in settings? Json time-value, raw value, valueId?
Hmm, thought I'd set to raw but was using json. Tried it as raw now though but there is no difference in result. The value in the UI stays empty. What I'm seeying though is that the manually  set value of `zwave/logeerkamer/crosstrainer/112/0/4` is removed after restarting the container while the value `zwave/logeerkamer/crosstrainer/112//4` is maintained. Not sure if that means anything.

**Comment by robertsLando** [comment] 2020-12-23 10:52
@jghaanstra are you using valueId topics or named? Anyway I suggest to use json-time value or valueId payloads, and remember that when you send commands you have to use that payload, you cannot use raw payload for commands if you have set json payloads

**Comment by robertsLando** [comment] 2020-12-23 10:57
@jghaanstra If you were using named topics there was a bug fixed with this PR: https://github.com/zwave-js/zwavejs2mqtt/pull/74

**Comment by jghaanstra** [comment] 2020-12-23 11:30
I'm using ValueID topics with "Just value" as payload type.

I'm about to give up on this though. I'll just put some duck tape over the LED or replace them with other sockets.

**Comment by AlCalzone** [comment] 2020-12-23 11:45
Uhh I just found something:
![grafik](https://user-images.githubusercontent.com/17641229/102993001-aa178100-451c-11eb-9405-01f1cfaf258b.png)

That explains why you had to frequently change parameter 1 to keep the light off...

**Comment by jghaanstra** [comment] 2020-12-23 11:51
Oh wow, that explains why I cant set these values. Nice find.

It's still strange though that trying to set this value within the timeout on zwave2mqtt actually resulted in the LED never blinking while I have not been able to achieve this on zwavejs2mqtt. I'll see if I can find a different configuration value that I can change every 4 hours to avoid the blinking.

Case closed and sorry for wasting everybody's time on this.

**Comment by AlCalzone** [comment] 2020-12-23 12:28
> It's still strange though that trying to set this value within the timeout on zwave2mqtt actually resulted in the LED never blinking while I have not been able to achieve this on zwavejs2mqtt.

I can't explain that. Both drivers send the same (standardized!) commands, so there shouldn't be any difference.
