### ISSUE TITLE
[bug] Device Configuration - not working

### ISSUE THREAD

**Issue by Masterz69** [zwave-js/zwavejs2mqtt#844] opened 2021-03-08 21:04 UTC
Issue about changing device configuration from ZWaveJS Control Panel - IMHO there is nothing about HA.

Version info: HA Core 5.12 on RP4 4G + Aeotec Z-Wave Stick Gen5. 
![image](https://user-images.githubusercontent.com/15225823/110380479-d6916280-8060-11eb-88e0-2b91e40a81c6.png)

ZWave device: Shenzhen Neo Electronics Co., Ltd. NAS-WR01ZE
See attached JSON ZiP:
[node_2.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6104068/node_2.zip)

Basic functions, like switching and measurements looks working.

Tried to disable button on device, by using 
![image](https://user-images.githubusercontent.com/15225823/110381169-c8901180-8061-11eb-8f4e-9984055b8a45.png)

Whch is decribed in [manual ](https://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1783/Smart-Plug%20User%20Guide%20V2.doc)as following:
Function:	Enable Button On/Off
Parameter Number:  10.
Parameter Size:	1 Byte
Available Settings： 0, 1.
Default Setting:	1

Immediately after selecting "Disable Button" and pressing arrow in log appears:
2021-03-08 22:59:29.169 DEBUG SOCKET: Event ZWAVE_API emitted to toZSjkq3V9Aj4DM3AAAL
2021-03-08 22:59:29.173 INFO ZWAVE: Calling api writeValue with args: [ { nodeId: 2, commandClass: 112, property: 10 }, 0, [length]: 2 ]
2021-03-08 22:59:29.176 INFO ZWAVE: Writing 0 to 2-112-0-10
2021-03-08 22:59:29.231 INFO ZWAVE: Success zwave api call writeValue { success: true, message: 'Success zwave api call', result: undefined }
2021-03-08 22:59:30.296 INFO ZWAVE: Node 2: value updated: 112-0-10 0 => 13

But device button still operable, configuration not changed, looks like.

In same way tried to change "[2-112-0-7] Remember Relay ON/OFF status after power failure." or "[2-112-0-2] Meter Report Interval" - nothing works..

Not sure, but looks like not any value of configuration item actually are retrieved from device, see only fake numbers -not default values, as must be on device with factory settings:
![image](https://user-images.githubusercontent.com/15225823/110381689-80252380-8062-11eb-8c37-a59fae0adb22.png)

**Comment by robertsLando** [comment] 2021-03-09 07:23
@Masterz69 That's strange. Could you attach a full `silly` level log of zwavejs?

**Comment by robertsLando** [comment] 2021-03-09 10:08
@AlCalzone Seems like the config options values are out of the range of the allowed options, the strange thing is that the allowManualEntry is not true and also when he try to set a value the feedback tells another value is set (try to write 0 and updates it to 13)

**Comment by AlCalzone** [comment] 2021-03-09 10:20
I can't make out which device that is exactly, but our config file seems to be wrong. Config parameter #5 returns a value of 120 but our config thinks this stands for Enabled/Disabled.
@Masterz69 please share the device ID or our config browser link and the firmware version.

> when he try to set a value the feedback tells another value is set (try to write 0 and updates it to 13)

No, the 0 is being set but the device does not accept it and returns 13 instead

That being said - zwavejs2mqtt **needs** to be able to display values that are out of range. It looks like the values are missing when they are not. This will not be the last time that we have an incorrect config file.

**Comment by robertsLando** [comment] 2021-03-09 10:22
> That being said - zwavejs2mqtt needs to be able to display values that are out of range. It looks like the values are missing when they are not. This will not be the last time that we have an incorrect config file.

Yep I'm on this right now :+1:

**Comment by Masterz69** [comment] 2021-03-09 11:04
Both right now connected devices are identical. Tried to configure node 2.

As far I see in json file: deviceId":"600-4135-512",
"manufacturer":"Shenzhen Neo Electronics Co., Ltd.",
"manufacturerId":600,"productType":512,"productId":4135, ... 
"productLabel":"NAS-WR01ZE","productDescription":"Wall Plug Switch",

Purchased it from [that Ali seller](https://aliexpress.ru/item/32868985571.html) - there no model name, unfortunately.
Looking on products.z-wavealliance.org - [found that one](https://products.z-wavealliance.org/products/1783?selectedFrequencyId=1).

As far I see configuration page based on this ^^ product info.

But let see some photo from in package included manual:
![20210309_125420](https://user-images.githubusercontent.com/15225823/110460590-1004b500-80d7-11eb-8d00-c388552db730.jpg)
Here parameter 5 is exactly 120 as a default value. At least manual and device say same data.

![20210309_125510](https://user-images.githubusercontent.com/15225823/110461273-e4ce9580-80d7-11eb-8536-a569e6fed322.jpg)

"please share the device ID or our config browser link and the firmware version."
^^ not sure what provide all You asked. if no - let me know.

**Comment by Masterz69** [comment] 2021-03-09 11:10
Pls see information about same plug from Hubitat Elevation:
deviceId: 4135
deviceType: 512
manufacturer: 600
inClusters: 0x5E,0x98,0x9F,0x55,0x73,0x86,0x85,0x8E,0x59,0x72,0x5A,0x25,0x32,0x71,0x70,0x6C
zwNodeInfo: D3 9C 00 04 10 01 5E 98 9F 55 73 86 85 5C 8E 59 72 5A 25 32 71 70 6C 68 23
properties: measure-power
firmwareVersion: 2.23
protocolVersion: 6.04
hardwareVersion: 16

deviceId, deviceType, manufacturer - same one. Probably here is a plug firmware version, not sure.

Just guess, may be with another firmware/hardware version changed also parameters etc....?

**Comment by Masterz69** [comment] 2021-03-09 11:22
Found previously created issue "[Add missing Neo Coolcam device (INFO ZWAVE: Node 6 ready: Unknown manufacturer 600 - Unknown product 4135 (512))](https://github.com/zwave-js/node-zwave-js/issues/1283)" & "[Add missing Neo Coolcam devices](https://github.com/zwave-js/node-zwave-js/issues/1221)".

In @ookonbekend comment I see link to 
https://github.com/OpenZWave/open-zwave/blob/master/config/shenzen_neo/nas-wr01ze.xml
^^ this looks right one for that device.

**Comment by Masterz69** [comment] 2021-03-09 11:27
Looks like I found config link; https://devices.zwave-js.io/?jumpTo=0x0258:0x0200:0x1027:null

Probably there must be a new config for V2.

Kindly asking to add it, it would be great !

Thank You in advance.

**Comment by AlCalzone** [comment] 2021-03-09 11:43
Duplicate of https://github.com/zwave-js/node-zwave-js/issues/1221

**Closed** 2021-03-09 12:36 UTC
Labels: bug
