### ISSUE TITLE
[Bug]: UI issues since 6.15.0

### ISSUE THREAD

**Issue by alexdelprete** [zwave-js/zwavejs2mqtt#2565] opened 2022-08-03 00:22 UTC
### Checklist

- [X]  I am not using Home Assistant. Or: a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is not described there.
- [X] I have read the changelog and my problem is not mentioned there.

### Deploy method

Docker

### Zwavejs2Mqtt version

6.15.0 / 6.15.1

### ZwaveJS version

9.6.2

### Describe the bug

UI issues since 6.15.0, tried with 6.15.1, same issue:

![image](https://user-images.githubusercontent.com/7027842/182498379-e9b99231-9cb5-4324-9b6a-f29b8153c320.png)

I downgraded to 6.14.1 and UI is ok again:

![image](https://user-images.githubusercontent.com/7027842/182498485-f1b4c65c-5650-40b1-a800-ec9ecda43a67.png)

### To Reproduce

just upgrade to 6.15.0

### Expected behavior

correct UI

**Comment by adamjernst** [comment] 2022-08-03 02:52
Dupe of #2564.

**Comment by alexdelprete** [comment] 2022-08-03 02:54
> Dupe of #2564.

It's not the same issue. And 6.15.1 didn't fix it, as I wrote in the OP.

**Comment by robertsLando** [comment] 2022-08-03 06:13
> It's not the same issue. And 6.15.1 didn't fix it, as I wrote in the OP.

It is, I think you may have something cached in browser, after upgrading to 6.15.1 try to press Ctrl+F5 to force refresh the page

**Comment by alexdelprete** [comment] 2022-08-03 11:45
hard refresh is the first thing I tried obviously, I also tried from a browser in a VM which I never used to access zwavejs2mqtt. it didn't work for me. went back to 6.14.1 for now.

**Closed** 2022-08-03 11:50 UTC
Labels: bug

**Comment by robertsLando** [comment] 2022-08-03 12:01
> Did you change 6.15.1? Anyway, all set now, thank you. :)

I didn't changed anything, I think that for some reason the first pull you tried may have failed 🤷🏼‍♂️ 

Felice che ora ti funzioni 😄

**Comment by alexdelprete** [comment] 2022-08-03 12:05
> I think that for some reason the first pull you tried may have failed

That is weird. But who knows. :)

> Felice che ora ti funzioni

Sei italiano? Non lo sapevo. :)

**Comment by robertsLando** [comment] 2022-08-03 12:06
> Sei italiano? Non lo sapevo. :)

Si, dal Veneto :)

**Comment by alexdelprete** [comment] 2022-08-03 12:07
> Si, dal Veneto :)

Grande! Grazie per tutto il lavoro che fai su questo progetto.
