### ISSUE TITLE
Log Rotation[feat]

### ISSUE THREAD

**Issue by kevinkahn** [zwave-js/zwavejs2mqtt#879] opened 2021-03-13 02:38 UTC
**Is your feature request related to a problem? Please describe.**
Log files can grow pretty large after things are running for an extended time

**Describe the solution you'd like**
Either add log rotation to the server and have it move  log files to .1, .2 etc, as say Linux syslog does, or failing that, don't keep the log file open between entries.  As things stand, you can't easily do the rotation externally by renaming the logfile and letting the server build a new one by opening the now non-existent name.  Tried this but the server holds the file open so new log entries just keep getting added to the now renamed log file.

**Describe alternatives you've considered**
The only real alternative is to copy the current log file to a new file and then empty the existing file.  This is both somewhat expensive (copying a large file) and logically incorrect since you cannot guarantee that you won't miss a log entry (copy file, entry occurs, 0 log file case).

**Additional context**
This is probably low priority but given that in principle the server in a stable situation can be running for months or even years, just continuing to add to the single log file seems poor practice.

**Comment by robertsLando** [comment] 2021-03-15 10:24
Duplicate of #298

**Closed by robertsLando** 2021-03-15 10:24 UTC
Labels: enhancement
