### ISSUE TITLE
Smart Start: iPhone - Fails to find a QR/DSK code

### ISSUE THREAD

**Issue by doug62** [zwave-js/zwavejs2mqtt#1958] opened 2021-11-11 05:27 UTC
### Version

**Checklist:**

- [ x ] I am **not** using Home Assistant. **Or:** a developer has told me to come here.
- [ x ] I have checked the troubleshooting section and my problem is **not** described there.
- [ x ] I have read the changelog and my problem is **not** mentioned there.

Build/Run method

- [ x ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

Zwavejs2Mqtt version:  5.11.0
Z-Wave JS version: 8.7.5

### Describe the bug

SmartStart/+/(select qr/cam icon)/Import

On iphone clicking Drop... activates camera, on desktop a file can be dragged.

In either case - no QR code is found.

### Expected behavior

QR Code is recognized

**Comment by robertsLando** [comment] 2021-11-11 07:21
@doug62 Duplicate of #1936

**Comment by doug62** [comment] 2021-11-11 07:46
To be clear - this bug is about how images acquired either by direct cam or file fail to be recognized - not the process of acquiring images

**Comment by robertsLando** [comment] 2021-11-11 08:41
Humm do you get any error on console? I cannot reproduce it with my codes. Could you send me your qr code via email?

**Comment by doug62** [comment] 2021-11-11 13:16
![t](https://user-images.githubusercontent.com/5632034/141304593-07b1f4ac-3e4f-40d2-b6d8-1b96edf6ef68.jpg)

**Closed** 2021-11-11 15:43 UTC
Labels: bug
