### ISSUE TITLE
[bug] Memory leak? FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Br-ian** [zwave-js/zwavejs2mqtt#978] opened 2021-03-31 11:30 UTC
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker

zwavejs2mqtt version: latest docker image, can't open control panel due to this bug so I cannot check exactly
zwave-js version: latest docker image, can't open control panel due to this bug so I cannot check exactly

### Describe the bug

Whenever I try to start the Docker container, I get the following fatal error:

```
<--- Last few GCs --->

[1:0x55a7f40]    23467 ms: Scavenge 998.1 (1035.9) -> 996.3 (1036.9) MB, 18.3 / 0.0 ms  (average mu = 0.911, current mu = 0.785) allocation failure
[1:0x55a7f40]    23509 ms: Scavenge 999.2 (1036.9) -> 998.2 (1041.6) MB, 23.4 / 0.0 ms  (average mu = 0.911, current mu = 0.785) allocation failure
[1:0x55a7f40]    23714 ms: Mark-sweep 1003.8 (1041.6) -> 1002.0 (1048.9) MB, 168.6 / 0.1 ms  (average mu = 0.857, current mu = 0.701) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

free -h:

```
              total        used        free      shared  buff/cache   available
Mem:          7.6Gi       1.6Gi       3.8Gi       157Mi       2.3Gi       5.7Gi
Swap:         2.0Gi          0B       2.0Gi
```

My platform is a Raspberry Pi 4 - 8GB. 

### To Reproduce

Unclear how to reproduce this bug, it started happening after +/- 2 weeks of run time. 

### Expected behavior

I expect the Docker container to start successfully, not crash and restart non-stop.

### Additional context

Relevant docker logs:

```
-- Logs begin at Wed 2021-03-31 13:15:38 CEST, end at Wed 2021-03-31 13:26:30 CEST. --
Mar 31 13:15:46 pi dockerd[939]: time="2021-03-31T13:15:46.704329902+02:00" level=warning msg="Your kernel does not support cgroup memory limit"
Mar 31 13:15:46 pi dockerd[939]: time="2021-03-31T13:15:46.704400754+02:00" level=warning msg="Your kernel does not support cgroup rt period"
Mar 31 13:15:46 pi dockerd[939]: time="2021-03-31T13:15:46.704479087+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Mar 31 13:15:46 pi dockerd[939]: time="2021-03-31T13:15:46.704512717+02:00" level=warning msg="Your kernel does not support cgroup blkio weight"
Mar 31 13:15:46 pi dockerd[939]: time="2021-03-31T13:15:46.704543013+02:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Mar 31 13:16:39 pi dockerd[939]: time="2021-03-31T13:16:39.605584622+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 31 13:16:39 pi dockerd[939]: time="2021-03-31T13:16:39.619436882+02:00" level=warning msg="e7963ea21f4f903b8ae6aba58422378c1edc19347b772083925b810cacf9e5a8 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e7963ea21f4f903b
Mar 31 13:17:07 pi dockerd[939]: time="2021-03-31T13:17:07.664080324+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 31 13:17:07 pi dockerd[939]: time="2021-03-31T13:17:07.695350782+02:00" level=warning msg="e7963ea21f4f903b8ae6aba58422378c1edc19347b772083925b810cacf9e5a8 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e7963ea21f4f903b
Mar 31 13:17:42 pi dockerd[939]: time="2021-03-31T13:17:42.900951986+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 31 13:17:42 pi dockerd[939]: time="2021-03-31T13:17:42.941397827+02:00" level=warning msg="e7963ea21f4f903b8ae6aba58422378c1edc19347b772083925b810cacf9e5a8 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e7963ea21f4f903b
Mar 31 13:18:22 pi dockerd[939]: time="2021-03-31T13:18:22.756910611+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 31 13:18:22 pi dockerd[939]: time="2021-03-31T13:18:22.799604271+02:00" level=warning msg="e7963ea21f4f903b8ae6aba58422378c1edc19347b772083925b810cacf9e5a8 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e7963ea21f4f903b
Mar 31 13:19:02 pi dockerd[939]: time="2021-03-31T13:19:02.836339345+02:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Mar 31 13:19:02 pi dockerd[939]: time="2021-03-31T13:19:02.864552733+02:00" level=warning msg="e7963ea21f4f903b8ae6aba58422378c1edc19347b772083925b810cacf9e5a8 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/e7963ea21f4f903b
[is spammed continously]
```

**Comment by Br-ian** [comment] 2021-03-31 11:51
After enabling the memory cgroup I can actually monitor the memory usage of the container. After ~10 seconds it is at ~1.2GiB

```
e7963ea21f4f        zwavejs2mqtt        93.28%              1.214GiB / 7.64GiB   15.89%              0B / 0B             0B / 0B             11
```

At which point it is killed.

**Comment by Br-ian** [comment] 2021-03-31 11:59
Apologies for the spam, the issue was that in the mqtt folder, the outgoing file was 1.9GB as the system had lost connection to MQTT for some amount of time, and then it rebooted. There are a lot of nodes in the network so I guess the messages accumulated quite quickly.

I guess there a few options here:

- Limit the file size of the mqtt buffer
- Don't try to read the entire buffer in one go
- Split up the buffer in multiple files

**Comment by robertsLando** [comment] 2021-03-31 13:15
Also by default db doesn't have a way to limit it's size, it keeps storing messages while iit's offline. I suggest you to keep that disabled, I dunno if I will fix that as it's a problem on mqtt side

**Comment by robertsLando** [comment] 2021-04-11 09:37
Duplicate of #220

**Closed** 2021-04-11 09:36 UTC
Labels: bug
