### ISSUE TITLE
[bug] Page deep-links and browser reloads always switch to control panel

### ISSUE THREAD

**Issue by ahochsteger** [zwave-js/zwavejs2mqtt#675] opened 2021-02-22 06:45 UTC
### Version

Build/Run method: Docker
zwavejs2mqtt version: 1.2.2
zwavejs version: 6.4.0

### Describe the bug

When I reload a page other than the control panel it always switches back to the control panel.

### To Reproduce

Steps to reproduce the behavior for browser reload:

1. Go to any page other than the control panel (e.g. the settings page)
2. Click on reload in the browser
3. The browser changes the URL to the control panel

Steps to reproduce the behavior for deep-linking:

1. Open a direct link to any page other than the control panel (e.g. .../settings)
2. The browser changes the URL to the control panel

### Expected behavior

The browser should keep the current URL on reload or stay at the given URL when using a direct link.

### Additional context

It seems that this behavior change has been introduced with #591 and #640.

**Comment by ahochsteger** [comment] 2021-02-22 06:47
The fix will also be required to be able to allow more fine-grained deep links in z2m e.g. direct link to certain nodes or tabs in the control panel to allow switching between mesh graph and control panel or direct link from other smart home systems to manage a specific node.

**Comment by robertsLando** [comment] 2021-02-22 09:52
> The fix will also be required to be able to allow more fine-grained deep links for z2m in the future e.g. direct link to certain nodes or tabs in the control panel to allow switching between mesh graph and control panel or direct link from other smart home systems to manage a specific node.

**Comment by robertsLando** [comment] 2021-02-22 09:52
About the main issue, I think this is something that only happens in production right? as I'm not able to repro this in my dev env

**Comment by robertsLando** [comment] 2021-02-24 13:39
I'm unable to reproduce this on my instance in dev or production env :man_shrugging:

**Comment by ahochsteger** [comment] 2021-02-28 09:25
@robertsLando sorry, for the late reply - here is some more information that may help to reproduce the issue:
* I can reproduce the issue in production (rpi4 using docker) as well as running it on a dev setup (without docker)
* I have the internal auth mechanism disabled, since I'm using traefik with forwarded auth to Google Authentication instead for all of my apps
* When I enter the URL `/settings` I can see redirects to `/` and then to `/control-panel` in the address bar of the browser

Did you try to reproduce it with auth enabled? I suspect that this behavior has been introduced with the auth changes.

**Comment by ahochsteger** [comment] 2021-03-05 15:44
@robertsLando I just found some time to debug this issue and added some logs to output variables that affect the control flow. This is the log output when accessing the settings page:
```
Navigated to http://localhost:8092/settings
index.js?a18c:150 beforeEach(): user.notLogged: true ,route.auth: true ,to.fullPath: /settings , from: {name: null, meta: {…}, path: "/", hash: "", query: {…}, …}
index.js?a18c:150 beforeEach(): user.notLogged: true ,route.auth: false ,to.fullPath: / , from: {name: null, meta: {…}, path: "/", hash: "", query: {…}, …}
App.vue?c65d:500 checkAuth() newAuth: false , oldAuth: undefined , this.$route.path: /
```
I'm not really sure about the meaning of all variables but as you can see the router redirects form /settings to / and stays there.

It's only happening, if auth is disabled (since I offload auth to traefik). When auth is enabled this is not happening.

**Comment by robertsLando** [comment] 2021-03-05 19:50
I think your problem could be that the user is not found in localstorage, this happens in router/index in beforeeach functuon, I suggest you to put a breakpoint there and see if the user is found

**Comment by ahochsteger** [comment] 2021-03-05 20:17
Yes, there is no user found in localStorage, but I don't get why it should find one, since I'm running zjs2m with authentication disabled (as I already pointed out before).
These are the log outputs from the relevant locations:
```
beforeEach() store.state.user: {__ob__: Observer}__ob__: Observer {value: {…}, dep: Dep, vmCount: 0}__proto__: Object
beforeEach() user(from localStorage): null
beforeEach() user: {}
```

**Comment by robertsLando** [comment] 2021-03-08 08:30
Sorry I misunderstood the problem, I thought the problem was with auth enabled. Let me check this again

**Comment by robertsLando** [comment] 2021-03-09 13:06
I have submitted a fix for this, try it out

**Closed** 2021-03-09 14:23 UTC
Labels: bug

**Comment by robertsLando** [comment] 2021-03-09 14:29
It should also don't break when it is enabled. Could you double check? :)

**Comment by ahochsteger** [comment] 2021-03-09 15:02
@robertsLando it works with auth enabled and disabled :-).
What I don't understand is, why there is some difference when auth is disabled that causes opening `/settings` to redirect to `/` and than back to `/settings`. Are they required?
I don't see these redirects when auth is enabled.

**Comment by ahochsteger** [comment] 2021-03-09 15:29
I see - so you're currently using a workaround to solve this problem until a better solution can be found.
Thanks - it works now again as expected :-).
