### ISSUE TITLE
[bug] UI ignores association group naming from device files

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwavejs2mqtt#420] opened 2021-02-02 00:50 UTC
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0
zwavejs version: 6.0.0

### Describe the bug

The UI displays the association group name from the device even where we have a corrected description in the device file. An example is the GE 14291 device file where we have renamed Group 2 to 'Local Control' and Group 3 to 'Double Tap'. Both show as "On/Off Control" in the UI. 

I'm unsure if this is a bug at the Zwave2jsmqtt or node-zwave-js level. @AlCalzone ?

Where we are specifying the association groups, we should respect what is in the device file. We're removing those for all zwave plus devices without a special need for the association groups to be defined anyway.

### Expected behavior

Respect device file naming.

**Comment by AlCalzone** [comment] 2021-02-02 07:32
Duplicate of https://github.com/zwave-js/node-zwave-js/issues/1304

**Comment by robertsLando** [comment] 2021-02-02 08:50
Closing this here

**Closed by robertsLando** 2021-02-02 08:50 UTC
Labels: bug
