### ISSUE TITLE
[bug] Config Update doesn't happen

### ISSUE THREAD

**Issue by embcla** [zwave-js/zwavejs2mqtt#1138] opened 2021-05-05 08:46 UTC
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )
- [x] homeassistant

zwavejs2mqtt version: 4.0.1
zwave-js version: 7.3.0

### Describe the bug

The ui shows a configuration update available, upon clicking to perform it, it is reported as successfully done but the icon stays in notification mode.

### To Reproduce

I just have it right out of the box

### Expected behavior

I'd expect the icon to go away/inactive and some kind of refresh to happen

### Additional context

![image](https://user-images.githubusercontent.com/54371771/117116855-26ee1d80-ad8f-11eb-898e-0247380cfabe.png)
![image](https://user-images.githubusercontent.com/54371771/117116883-2f465880-ad8f-11eb-9665-7239549412ea.png)
![image](https://user-images.githubusercontent.com/54371771/117117082-6a488c00-ad8f-11eb-92c8-217cc85e38ad.png)

**Comment by robertsLando** [comment] 2021-05-05 09:00
Duplicate of #1131

**Closed by robertsLando** 2021-05-05 09:00 UTC
Labels: bug
