### ISSUE TITLE
[question] Yale YRD256 how to get status?

### ISSUE THREAD

**Issue by mmiller7** [zwave-js/zwavejs2mqtt#2340] opened 2022-03-27 16:48 UTC
First question I guess, I'm using ZwaveJS to MQTT (not "default" ZwaveJS from Home Assistant), so I don't know if I can refer to the "plain" ZwaveJS documents which make it sound like what I want is impossible.

I'm in the process of rebuilding my Zwave network with a new Aeotec v7 stick and ZwaveJS to MQTT before the "old" Home Assistant Zwave goes away in the next update.

Today I've been fighting with the Yale YRD256 deadbolts, I moved one of them over to the new Zwave JS to MQTT network and I'm trying to make it work properly, but the only thing that is working seems to be basic locked/unlocked state.

Ever since I paired it, it's shown as "Jammed" which is wrong.  Operating the lock unlocked/relocked is not clearing the "jammed" state as it did with old Z-Wave.  This is one of the most important things to me as people (especially guests) don't fully latch the door and it then can't lock - which means someone has to go check it, so I have a notification to message us any time a lock jams as well as when it operates to unlocked/locked so we know it was cleared.  How can I get it to correctly get "jammed" status?

The "keypad disabled for too many tries" also have the same issue as "jammed", even after I take action (like mechanically cycling the bolt) to reset it or eve waiting for the timeout to elapse and unlocking with an authorized code I am still seeing it report as "disabled" on the binary sensor.  How can I correctly get "too many attempts" status?

I also have some events that depend on knowing if it was unlocked/locked by the keypad or the mechanical knob.  So far I'm not finding any way to get that information.  How can I find out if the lock was operated by the manual mechanical override or the keypad?

I don't see any information about some of the tamper alarms either (like keypad removed) reported.  How would I get those?

So far I'm sorry to say that this migration has been a very poor experience.  So many things that "just worked" out of the box per the manufacturer documentation now seem to be really hard or some claim not possible at all.

Help?

**Comment by robertsLando** [comment] 2022-03-28 07:15
@mmiller7 is this value also shown in UI? Is it different from the one sent in MQTT?

**Comment by mmiller7** [comment] 2022-03-29 13:11
> 

Yes, it seems to show the same everywhere.  The status for "motor jammed", "pin tries exceeded keypad lockout", and "RF module power restored" (aka "installed the batteries") are all now permanently stuck "on".

I've since learned a lot more, it sounds like multiple things are affected by this issue actually now:
https://github.com/zwave-js/node-zwave-js/issues/1543

![image](https://user-images.githubusercontent.com/606945/160617694-3afd69ef-8a54-4581-aedb-1bb3976044ff.png)

I also found apparently the guide that I was following saying to look at `zwave_js_event` and `zwave_js_value_notification` was wrong and it should have been `zwave_js_notification` to get the "successful normal" lock/unlock events.

And it looks like I can see the "alarm" events re-fire a value-updated (same value) if the fault re-occurrs in the debug-messages, but they never actually clear when you cycle the bolt manually like I expect them to.  The lock in real life gives the "beep-boop" noise that its happy again and will begin functioning normally but the zwave status never actually refreshes.

**Comment by robertsLando** [comment] 2022-03-29 15:29
@mmiller7 Firstly you was speaking about MQTT but when you mention `zwave_js_event` ans `zwave_js_value_notification` you might refer to home assitant zwave-js server?

**Comment by mmiller7** [comment] 2022-03-29 21:16
> @mmiller7 Firstly you was speaking about MQTT but when you mention `zwave_js_event` ans `zwave_js_value_notification` you might refer to home assitant zwave-js server?

I've been trying to use ZwaveJS to MQTT (addon) with ZwaveJS (integration) on Home Assistant, but the results are not sane.  Some things are either not working well or don't appear to be passed along.

In attempts to find a way to debug, I temporarily turned on MQTT (which I'd prefer not to use) and can see some of the things I want showing up in a MQTT Explorer in a way that makes sense (timestamp updates each time a condition is reported by the lock, but I don't see it showing up in a sane way on Home Assistant nor the ZwaveJS to MQTT (addon) web-UI.

For example, when a jam condition occurs I observe the following:
- MQTT Explorer looks like the conditions for a jam only get pushed when a jam occurrs
- ZwaveJS-to-MQTT web-UI always reports a jam, whether or not its jammed
- Home Assistant binary sensor always reports a jam, whether or not its jammed

It seems like the statuses are not properly in sync when the fault conditions are resolved and a lock/unlock completes successfully to reset the lock.

**Comment by robertsLando** [comment] 2022-03-30 06:34
Ok so the problem is not with mqtt, the problem is with hass components that are not showing correct state. This is not something I can fix as I have no control on what hass does. You should open your issue to hass core repo instead

**Comment by mmiller7** [comment] 2022-03-30 12:57
> Ok so the problem is not with mqtt, the problem is with hass components that are not showing correct state. This is not something I can fix as I have no control on what hass does. You should open your issue to hass core repo instead

What about it also not showing correct in the zwavejs to mqtt addon (neither hass nor mqtt)?

I didn't think the Web UI dashboard for the addon was run by Home Assistant, but was from the addon itself?  That screenshot I posted was from Supervisor > Addons > ZwaveJS-to-MQTT > Devices > Expand my lock > Notifications v4.

**Comment by robertsLando** [comment] 2022-03-30 15:21
@AlCalzone

**Comment by AlCalzone** [comment] 2022-03-30 20:03
I think this is a duplicate of https://github.com/zwave-js/node-zwave-js/issues/1543

Lock jammed is a stateful notification variable, but we don't model any interaction between different notifications variables and events, mainly because the specifications don't mention any interactions.
In this case, the lock reports jammed, but never sets that variable back to idle - and we don't (yet) treat successful lock/unlock attempts as "no longer jammed".

**Comment by robertsLando** [comment] 2022-05-09 09:27
Follow updates [there](https://github.com/zwave-js/node-zwave-js/issues/1543) so

**Closed by robertsLando** 2022-05-09 09:27 UTC
Labels: question
