### ISSUE TITLE
[bug] ZEN30 switch does not update status

### ISSUE THREAD

**Issue by praveen12bnitt** [zwave-js/zwavejs2mqtt#1249] opened 2021-05-20 12:14 UTC
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 4.2.1
zwave-js: 7.4.0

### Describe the bug

I have a [ZEN30](https://www.thesmartesthouse.com/products/zooz-z-wave-plus-s2-double-switch-zen30-white-for-light-fan-combo) switch. The problem that i am having is, if i use the switch physically, it does not update the status in zwaavejs2mqtt UI. I see this behavior for both the "MultiLevel Switch". The binary switch appears to work fine. 

When i do the same via Home Assistant ( integration with HA is done with MQTT), i see the value getting updated properly.

### To Reproduce

Physically "turn on" the switch. Go to the the node and check the "currentValue" for the node.  It will continue to show it "0"
Clicking on the "refresh", it changes to "99".

When i go to MQTT and set zwave2mqtt/LivingRoom/38/0/targetValue/set to 99, it turns on the light and updates the status in zwavejsmqtt UI automatically. 

### Expected behavior
When i turn on the switch physically, it should update the status in the UI. 

### Additional context

Debug logs when i turn on the switch physically.
2021-05-20 12:08:51.143 INFO ZWAVE: Node 16: value notification: 91-0-scene-001 0
2021-05-20 12:08:52.130 INFO ZWAVE: Node 16: value updated: 32-1-currentValue 0 => 99
2021-05-20 12:08:52.132 INFO ZWAVE: Node 16: value updated: 37-1-currentValue false => true

If you notice the logs, it says "32-1-currentValue 0 => 99". But i think it should update "38-0"
I also dont know why its updating "37-1". 

[device.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6515783/device.json.zip)

**Comment by robertsLando** [comment] 2021-05-20 14:08
@AlCalzone Any reason why I don't get an update event of 38-0-currentValue too?

**Comment by AlCalzone** [comment] 2021-05-20 15:36
Duplicate of https://github.com/zwave-js/node-zwave-js/issues/2536

**Closed by AlCalzone** 2021-05-20 15:36 UTC
Labels: bug
