### ISSUE TITLE
MQTT not connecting on interview from dead to complete

### ISSUE THREAD

**Issue by hi-flyer** [zwave-js/zwavejs2mqtt#1642] opened 2021-09-01 15:20 UTC
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

Yes, my problem is within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
interview on a dead status to re-establish as live status

What do you observe?
JS control panel can actuate the Bail Blind after the status is shown as live. 
MQTT command to actuate the blind is ignored.

What did you expect to happen?
The blind to go up or down based on the MQTT command

 1) create RF Path issue where Status becomes dead
 2) Fix RF Path issue
 3) Interview Dead device (ie ID=6) in my case
 4) issue command from JS Control panel to actuate blind up or down (and it works)
 5) Issue command to MQTT on broker to actuate blind up or down ( and command is ignored)
 6) Restart Docker JS container
 7) Issue command to MQTT on broker to actuate blind up or down (and command works)
  note: solution was to restart Docker container. Seems it should not have required a restart of Docker container!

### Device information

Manufacturer: Bali blind - Somfy Motorized Blind
Model name: RSZ1
Node ID in your network:6

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
zwavejs2mqtt: 5.5.1
zwave-js: 8.2.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

I had an RF path blockage between this blind and my ZooZ S2 hub. Fixed path issue and re interview ID=6 and while JS control panel actuated the blind the MQTT command to actuate the blind failed (I was monitoring the JS Debug capability). I restarted Docker container and then the MQTT commands were accepted. So I do not have a problem to solve but seems the connection between broker and the control panel is not being updated on the establishment of status change for a device.

Note: I was transitioning from zwave2mqtt to zwavejs2mqtt at the time and had issues with the schlage locks. (i did not have the security codes established). In trouble shooting this is when I apparently created the RF path issue to ID=6

### Attach Driver Logfile

[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/7092221/zwavejs2mqtt.log)
[zwavejs_2021-09-01.log](https://github.com/zwave-js/node-zwave-js/files/7092222/zwavejs_2021-09-01.log)

**Comment by AlCalzone** [comment] 2021-09-01 21:26
@robertsLando

**Comment by AlCalzone** [comment] 2021-09-01 21:27
@hi-flyer next time please read the template more carefully :)

![grafik](https://user-images.githubusercontent.com/17641229/131747566-ac7e61c6-dd7d-4ca2-a18c-a2d9d3d7c1c8.png)

**Comment by hi-flyer** [comment] 2021-09-01 22:16
I did an edit afterwords to change no to yes. Which Is why I did not see this. I really have no clue where the problem is!

**Comment by AlCalzone** [comment] 2021-09-02 05:50
It's okay, I moved the issue into the correct repo for you

**Comment by hi-flyer** [comment] 2021-09-02 13:06
Your answer is correct from the point of view that from the control panel I could activate the blind but when I sent the command to the MQTT broker it was ignored. I restarted docker and then the command sent to the broker worked.

I do not know why you are not seeing the message on the broker before the docker reset. I was monitoring the broker messages as well using mosquitto_sub and the zwavejs2mqtt debug screen. No action was preformed by zwavejs2mqtt when the command was sent to the broker. Don't know what else to tell you.

**Comment by hi-flyer** [comment] 2021-09-02 13:27
Found it. Try looking at this section
2021-09-01 11:50:46.634 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:01.867 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:06.487 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Down/set, <Buffer 74 72 75 65>
2021-09-01 11:51:13.899 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:32.375 INFO ZWAVE: Calling api writeValue with args: [
  { nodeId: 6, commandClass: 38, endpoint: 0, property: 'Up' },
  true,
  {},
  [length]: 3
]

**Comment by robertsLando** [comment] 2021-09-02 13:46
Found the answer of this on zwavejs logs:

```
2021-09-01T11:50:22.341Z CNTRLR   [Node 006] Interview stage completed: CommandClasses
2021-09-01T11:50:22.343Z CNTRLR   [Node 006] Interview stage completed: OverwriteConfig
2021-09-01T11:50:22.345Z CNTRLR   [Node 006] Interview completed
2021-09-01T12:08:02.851Z CNTRLR   Turning RF off...
2021-09-01T12:08:02.870Z CNTRLR » [Node 001] requesting node neighbors...
```

We turn RF off for a while when requesting node neighbors to fix some issues, this happens only on startup. The question is does zwavejs queue commands sent while RF is turned off? @AlCalzone

**Comment by hi-flyer** [comment] 2021-09-02 16:22
ok, but if the radio was off, why could I send commands from the controller and yet not have MQTT broker commands actuated on. 
If on the other hand it your answer, ok by me. I was only reporting what I had seen. Mine is working.
Do you wish me to close this issue?

**Comment by hi-flyer** [comment] 2021-09-02 16:48
I have had another look at the zwavejs2mqtt. log. The critical area that shows what happened is as below:
2021-09-01 11:50:18.588 INFO ZWAVE: Calling api refreshInfo with args: [ 6, [length]: 1 ]
2021-09-01 11:50:18.607 INFO ZWAVE: Node 6: interview started
2021-09-01 11:50:18.614 INFO ZWAVE: Success zwave api call refreshInfo undefined
2021-09-01 11:50:18.646 INFO ZWAVE: Node 6: interview stage PROTOCOLINFO completed
2021-09-01 11:50:18.980 INFO ZWAVE: Node 6: has returned from the dead
2021-09-01 11:50:19.049 INFO ZWAVE: Node 6: interview stage NODEINFO completed
2021-09-01 11:50:19.113 INFO ZWAVE: Node 6: interview stage NODEINFO completed
2021-09-01 11:50:19.163 INFO ZWAVE: Node 6: value added: 114-0-manufacturerId => 622
2021-09-01 11:50:19.164 INFO ZWAVE: Node 6: value added: 114-0-productType => 21075
2021-09-01 11:50:19.164 INFO ZWAVE: Node 6: value added: 114-0-productId => 23089
2021-09-01 11:50:19.232 INFO ZWAVE: Node 6: value added 6-114-0-manufacturerId => 622
2021-09-01 11:50:19.233 INFO ZWAVE: Node 6: value updated: 114-0-manufacturerId 622 => 622
2021-09-01 11:50:19.234 INFO ZWAVE: Node 6: value added 6-114-0-productType => 21075
2021-09-01 11:50:19.235 INFO ZWAVE: Node 6: value updated: 114-0-productType 21075 => 21075
2021-09-01 11:50:19.235 INFO ZWAVE: Node 6: value added 6-114-0-productId => 23089
2021-09-01 11:50:19.236 INFO ZWAVE: Node 6: value updated: 114-0-productId 23089 => 23089
2021-09-01 11:50:19.446 INFO ZWAVE: Node 6: value added: 134-0-libraryType => 3
2021-09-01 11:50:19.447 INFO ZWAVE: Node 6: value added: 134-0-protocolVersion => 4.33
2021-09-01 11:50:19.448 INFO ZWAVE: Node 6: value added: 134-0-firmwareVersions => 11.2,0.18
2021-09-01 11:50:19.448 INFO ZWAVE: Node 6: value added: 134-0-hardwareVersion => 255
2021-09-01 11:50:19.517 INFO ZWAVE: Node 6: value added 6-134-0-libraryType => 3
2021-09-01 11:50:19.518 INFO ZWAVE: Node 6: value updated: 134-0-libraryType 3 => 3
2021-09-01 11:50:19.519 INFO ZWAVE: Node 6: value added 6-134-0-protocolVersion => 4.33
2021-09-01 11:50:19.521 INFO ZWAVE: Node 6: value updated: 134-0-protocolVersion 4.33 => 4.33
2021-09-01 11:50:19.521 INFO ZWAVE: Node 6: value added 6-134-0-firmwareVersions => 11.2,0.18
2021-09-01 11:50:19.522 INFO ZWAVE: Node 6: value updated: 134-0-firmwareVersions 11.2,0.18 => 11.2,0.18
2021-09-01 11:50:19.522 INFO ZWAVE: Node 6: value added 6-134-0-hardwareVersion => 255
2021-09-01 11:50:19.523 INFO ZWAVE: Node 6: value updated: 134-0-hardwareVersion 255 => 255
2021-09-01 11:50:20.873 INFO ZWAVE: Node 6: value added: 128-0-level => 100
2021-09-01 11:50:20.874 INFO ZWAVE: Node 6: value added: 128-0-isLow => false
2021-09-01 11:50:20.937 INFO ZWAVE: Node 6: value updated: 128-0-level 100 => 100
2021-09-01 11:50:20.938 INFO ZWAVE: Node 6: value updated: 128-0-isLow false => false
2021-09-01 11:50:21.945 INFO ZWAVE: Node 6: value added: 38-0-targetValue => undefined
2021-09-01 11:50:21.947 INFO ZWAVE: Node 6: metadata updated: 38-0-Up
2021-09-01 11:50:21.948 INFO ZWAVE: Node 6: metadata updated: 38-0-Down
2021-09-01 11:50:22.056 INFO ZWAVE: Node 6: value added 6-38-0-targetValue => 0
2021-09-01 11:50:22.057 INFO ZWAVE: Node 6: value updated: 38-0-targetValue undefined => 0
2021-09-01 11:50:22.058 INFO ZWAVE: Node 6: value added: 38-0-duration => 0s
2021-09-01 11:50:22.059 INFO ZWAVE: Node 6: value added: 38-0-currentValue => 0
2021-09-01 11:50:22.133 INFO ZWAVE: Node 6: value updated: 38-0-targetValue 0 => 0
2021-09-01 11:50:22.133 INFO ZWAVE: Node 6: value added 6-38-0-duration => 0s
2021-09-01 11:50:22.133 INFO ZWAVE: Node 6: value updated: 38-0-duration 0s => 0s
2021-09-01 11:50:22.136 INFO ZWAVE: Node 6: value added 6-38-0-currentValue => 0
2021-09-01 11:50:22.137 INFO ZWAVE: Node 6: value updated: 38-0-currentValue 0 => 0
2021-09-01 11:50:22.190 INFO ZWAVE: Node 6: value added: 37-0-currentValue => false
2021-09-01 11:50:22.191 INFO ZWAVE: Node 6: value added: 37-0-targetValue => undefined
2021-09-01 11:50:22.197 INFO ZWAVE: Node 6: interview stage COMMANDCLASSES completed
2021-09-01 11:50:22.198 INFO ZWAVE: Node 6: interview stage OVERWRITECONFIG completed
2021-09-01 11:50:22.200 INFO ZWAVE: Node 6: interview stage COMPLETE completed
2021-09-01 11:50:22.217 INFO ZWAVE: Node 6: value added 6-38-0-targetValue => 0
2021-09-01 11:50:22.217 INFO ZWAVE: Node 6: value added 6-38-0-duration => 0s
2021-09-01 11:50:22.220 INFO ZWAVE: Node 6: value added 6-38-0-currentValue => 0
2021-09-01 11:50:22.220 INFO ZWAVE: Node 6: value added 6-38-0-Up => undefined
2021-09-01 11:50:22.220 INFO ZWAVE: Node 6: value added 6-38-0-Down => undefined
2021-09-01 11:50:22.224 INFO ZWAVE: Node 6: value added 6-37-0-currentValue => false
2021-09-01 11:50:22.225 INFO ZWAVE: Node 6: value added 6-37-0-targetValue => undefined
2021-09-01 11:50:22.226 INFO ZWAVE: Node 6: value added 6-37-0-duration => NaNs
2021-09-01 11:50:22.226 INFO ZWAVE: Node 6: value added 6-114-0-manufacturerId => 622
2021-09-01 11:50:22.226 INFO ZWAVE: Node 6: value added 6-114-0-productType => 21075
2021-09-01 11:50:22.227 INFO ZWAVE: Node 6: value added 6-114-0-productId => 23089
2021-09-01 11:50:22.227 INFO ZWAVE: Node 6: value added 6-134-0-libraryType => 3
2021-09-01 11:50:22.227 INFO ZWAVE: Node 6: value added 6-134-0-protocolVersion => 4.33
2021-09-01 11:50:22.227 INFO ZWAVE: Node 6: value added 6-134-0-firmwareVersions => 11.2,0.18
2021-09-01 11:50:22.228 INFO ZWAVE: Node 6: value added 6-134-0-hardwareVersion => 255
2021-09-01 11:50:22.228 INFO ZWAVE: Node 6: value added 6-128-0-level => 100
2021-09-01 11:50:22.228 INFO ZWAVE: Node 6: value added 6-128-0-isLow => false
2021-09-01 11:50:22.320 INFO ZWAVE: Node 6 ready: Springs Window Fashions - RSZ1 (Somfy Motorized Shade)
2021-09-01 11:50:22.321 INFO ZWAVE: Node 6: interview COMPLETED, all values are updated
2021-09-01 11:50:22.338 INFO ZWAVE: Node 6: value updated: 37-0-currentValue false => false
2021-09-01 11:50:22.340 INFO ZWAVE: Node 6: interview stage COMMANDCLASSES completed
2021-09-01 11:50:22.342 INFO ZWAVE: Node 6: interview stage OVERWRITECONFIG completed
2021-09-01 11:50:22.344 INFO ZWAVE: Node 6: interview stage COMPLETE completed
2021-09-01 11:50:22.345 INFO ZWAVE: Node 6: interview COMPLETED, all values are updated
2021-09-01 11:50:46.634 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:01.867 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:06.487 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Down/set, <Buffer 74 72 75 65>
2021-09-01 11:51:13.899 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:51:32.375 INFO ZWAVE: Calling api writeValue with args: [
  { nodeId: 6, commandClass: 38, endpoint: 0, property: 'Up' },
  true,
  {},
  [length]: 3
]
2021-09-01 11:51:32.376 INFO ZWAVE: Writing true to 6-38-0-Up
2021-09-01 11:51:32.859 INFO ZWAVE: Success zwave api call writeValue undefined
2021-09-01 11:51:57.347 INFO ZWAVE: Node 6: value updated: 38-0-targetValue 0 => 99
2021-09-01 11:51:57.352 INFO ZWAVE: Node 6: value updated: 38-0-duration 0s => 0s
2021-09-01 11:51:57.354 INFO ZWAVE: Node 6: value updated: 38-0-currentValue 0 => 99
2021-09-01 11:51:58.150 INFO ZWAVE: Calling api writeValue with args: [
  { nodeId: 6, commandClass: 38, endpoint: 0, property: 'Down' },
  true,
  {},
  [length]: 3
]
2021-09-01 11:51:58.151 INFO ZWAVE: Writing true to 6-38-0-Down
2021-09-01 11:51:58.195 INFO ZWAVE: Success zwave api call writeValue undefined
2021-09-01 11:52:22.582 INFO ZWAVE: Node 6: value updated: 38-0-targetValue 99 => 0
2021-09-01 11:52:22.584 INFO ZWAVE: Node 6: value updated: 38-0-duration 0s => 0s
2021-09-01 11:52:22.585 INFO ZWAVE: Node 6: value updated: 38-0-currentValue 99 => 0
2021-09-01 11:52:24.538 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:52:56.238 INFO MQTT: Message received on zwave/Blinds/FMRM-Door-blind/38/0/Up/set, <Buffer 74 72 75 65>
2021-09-01 11:53:06.899 INFO MQTT: Message received on zwave/Blinds/BEE-blinds/38/0/Up/set, <Buffer 74 72 75 65>
as you can see no action is being taken on the MQTT messages but action is being taken by the controller initiated command. The identified RF radio off command is much later than this.
in any case, do you wish me to close this issue?

**Comment by robertsLando** [comment] 2021-09-03 06:14
Could you set log level to debug please? You should see logs like `Subscribing to updates of <valueId>`, I have a feel that for some reason `topicValues` object has not an entry for it when you send those commands

**Comment by hi-flyer** [comment] 2021-09-03 12:24
I had turned off logging yesterday. move all js logs to a backup place and restarted both logs with debug level. so these are only a few minutes old. I also created an up command followed by a down command on both node 4 and node 6 which are the same bali blind type. Do you wish me to wait for a few hours and resend the logs?

I also notice HASS discovery is on but I do not use this function. I am leaving the same so as not to create more confusion for debug purpose.

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7105800/zwavejs2mqtt.log)
[zwavejs_2021-09-03.log](https://github.com/zwave-js/zwavejs2mqtt/files/7105801/zwavejs_2021-09-03.log)

**Comment by robertsLando** [comment] 2021-09-03 13:35
@hi-flyer Based on your logs I see the subscription is correctly setup, what I don't see is the node becoming dead and back to ready

**Comment by hi-flyer** [comment] 2021-09-03 15:26
So, is what you are asking for is me to recreate the disconnect (which I fixed previously) and then re-interview node 6 and send the logs again?

**Comment by robertsLando** [comment] 2021-09-03 15:27
Yeah, to reproduce the bug with debug log level turned on

**Comment by hi-flyer** [comment] 2021-09-03 15:48
Ok, I created the disabled by unplugging power to Node 6 and verified that Node 6 was dead. I then stopped logging. removed old logs and restarted logging so they would be clean logs. After verifying the logs were being created, I plugged Node 6 back in and check to see state of Node 6 which still showed dead. I then forced an interview process on Node 6 which worked and this is the logs I am now sending. Hopefully it is what you are looking for. Also turned off HASS before all of this.

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107108/zwavejs2mqtt.log)
[zwavejs_2021-09-03.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107109/zwavejs_2021-09-03.log)

**Comment by hi-flyer** [comment] 2021-09-03 15:52
Update on logs. I just pressed the down action but nothing happened like before. Sorry should have done it the first time Sending updated logs.
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107144/zwavejs2mqtt.log)
[zwavejs_2021-09-03.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107145/zwavejs_2021-09-03.log)

**Comment by hi-flyer** [comment] 2021-09-03 16:43
Additional info. I did nothing specific that I am aware of to affect anything (i.e. I did not restart the docker). But about 12:27 local I hit the down button on the blind and it worked. It seems to me that something happened automatically that fixed the problem. I am sending the updated logs again in case that helps to explain.

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107380/zwavejs2mqtt.log)
[zwavejs_2021-09-03.log](https://github.com/zwave-js/zwavejs2mqtt/files/7107382/zwavejs_2021-09-03.log)

**Comment by robertsLando** [comment] 2021-09-10 07:41
Could you try with: https://github.com/zwave-js/zwavejs2mqtt/pull/1671

**Comment by hi-flyer** [comment] 2021-09-10 11:23
sorry, I do not understand. How to I modify my system to do #1617 and then return to my current.
Is this  modify docker.compose.yml line image: zwavejs/zwavejs2mqtt:latest to image: zwavejs/zwavejs2mqtt:1617?

**Comment by robertsLando** [comment] 2021-09-10 11:35
You should use Dockerfile.contrib to build your own docker image using the branch of #1617. BTW I have asked some other guys to make the tests for me, I cannot reproduce the issue on my side

**Comment by hi-flyer** [comment] 2021-09-10 11:59
sorry, I have never done this before so I wish to be sure I understand. Are you saying I should execute the following:
docker stop
docker.contrib run --rm -it -p 8091:8091 --device=/dev/ttyACM0 -v $(pwd)/store:/usr/src/app/store robertslando/zwave2mqtt:latest

**Comment by robertsLando** [comment] 2021-09-10 12:36
It's on master now, what 20 minutes and it will be available using tag `master`. Closing this, feel free to reopen if the bug is still present

**Closed by robertsLando** 2021-09-10 12:36 UTC
