### ISSUE TITLE
Enerwave ZWN-SC7 Scene Controller

### ISSUE THREAD

**Issue by MYeager1967** [zwave-js/zwavejs2mqtt#1640] opened 2021-08-31 20:47 UTC
I have one of these scene controllers that I've been using with a Vera Plus for several years. It has never wanted to work with Home Assistant and, as it's on the compatibility list for zwaveJS, I figured things might work now. It does appear in the interface and it's correctly identified and everything, but I can't figure out how to get it to work. Anyone out there actually have one of these working in their system that could point me in the right direction? If it works on a 5 year old Vera, I can't see why it won't work here...

**Comment by robertsLando** [comment] 2021-09-01 06:10
@blhoward2 Something related to https://github.com/zwave-js/node-zwave-js/issues/2397 ?

**Comment by MYeager1967** [comment] 2021-09-05 01:54
Going to try to figure this out in a few days. Any chance you'd be willing to help out?

**Comment by blhoward2** [comment] 2021-09-06 13:46
It's possible. Some googling suggests it's complicated in any event. Here are steps under HomeSeer: https://forums.homeseer.com/forum/homeseer-products-services/system-software-controllers/hs4-hs4pro-software/1386053-7-button-scene-controller-enerwave-zwn-sc7-to-be-or-not-to-be

**Comment by AlCalzone** [comment] 2021-09-06 14:47
Eh, I'm not 100% sure what Homeseer configures there exactly, but I **think** those are multiple endpoints with associations to other nodes (or the controller) and the device sends scene activation commands via these associations.

@MYeager1967 Please make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs), loglevel `debug` or `silly`, re-interview your node and when that is done, **attach** the logfile here (via drag&drop).

**Comment by csanner** [comment] 2021-09-07 13:51
okay, NO idea if this helps or not, but this is how it was used with smartthings:
https://github.com/mattjfrank/ZWN-SC7-Enerwave-7-Button-Scene-Controller

**Comment by AlCalzone** [comment] 2021-09-07 16:19
Yeah, that helps. The device is configured using the `Scene Controller Configuration CC`, which tells it which `Scene Activation CC` commands to send for which button/group. I'm not sure if you can assign each button to a different association group, I'd need a log for that.

So the basic functionality should be supported in the driver - not sure if the applications have support yet.

**Comment by csanner** [comment] 2021-09-07 16:28
What kind of log can I get for you? I'll happily run it through its paces if I know where to grab the output from

**Comment by AlCalzone** [comment] 2021-09-07 16:42
The one I requested here: https://github.com/zwave-js/zwavejs2mqtt/issues/1640#issuecomment-913703115

**Comment by csanner** [comment] 2021-09-07 16:51
Ah, sorry. Missed that as I came in late.

That looks like I need the mqtt set up. I do not. (I tried switching so I could get the panel back after I first set the whole thing up and I could not get it working)

**Comment by AlCalzone** [comment] 2021-09-07 17:14
HomeAssistant also has a way to get the driver logs, but I don't know how.

**Comment by MYeager1967** [comment] 2021-09-08 01:07
Sorry I haven't been much help the past few days. I've been working WAY too much. I'll have a good chance to dig into this on Thursday afternoon (I hope). Let me know what I can do to help and how to do it and I'll be happy to oblige. I'd love to get this working without having to put it back on the Vera. I've even looked to see if there's something else out there that's more current that might work "out of the box"...

Looks like it restarted the whole thing when I enabled logging....
[zwavejs_2021-09-07.log](https://github.com/zwave-js/zwavejs2mqtt/files/7125031/zwavejs_2021-09-07.log)

**Comment by blhoward2** [comment] 2021-09-08 02:53
This is the modern replacement. https://www.thesmartesthouse.com/products/zooz-700-series-z-wave-plus-scene-controller-switch-zen32

**Comment by MYeager1967** [comment] 2021-09-08 14:55
How difficult is it to use this controller? I'm not against changing it out....

**Comment by blhoward2** [comment] 2021-09-08 18:29
In HA? Not at all. There is a blueprint for it. Pair it and then setup the automation:

![image](https://user-images.githubusercontent.com/33612110/132564969-9173c015-fec4-4086-b9fb-faa717b83198.png)

**Comment by csanner** [comment] 2021-09-09 14:20
I mean, that is cool and if I need more I'll probably be buying those. but I'd like to keep the hardware I already have if possible :)
And I'll happily help out with this in any way I can.

**Comment by AlCalzone** [comment] 2021-09-09 14:55
https://github.com/zwave-js/node-zwave-js/issues/3309 needs to be solved for full support in the driver. Shouldn't be too hard

**Comment by Ikcelaks** [comment] 2021-09-09 17:57
zwave-js/node-zwave-js#3313 should allow setting the `dimmingDuration`.

Ideally, though, I think it would be nice if clients supported directly calling the `set` API method to directly set both the `sceneId` and `dimmingDuration` in the same call. Home-Assistant supports this specifically for setting lock user-codes (which are very similar), but it doesn't have a way to generically invoke a command class API method as far as I can tell.

**Comment by MYeager1967** [comment] 2021-09-10 12:54
I'd like to keep the current hardware as well, as everyone already knows what each button does...

**Comment by Ikcelaks** [comment] 2021-09-14 21:18
This should now be fixed in release 5.6.0

**Comment by MYeager1967** [comment] 2021-09-15 01:06
I'm guessing this doesn't get us anywhere closer to the device actually working?

**Comment by robertsLando** [comment] 2021-09-15 06:18
Wait a moment I had a problem with 5.6 release

**Comment by AlCalzone** [comment] 2021-09-15 22:33
> I'm guessing this doesn't get us anywhere closer to the device actually working?

You can now set the dimming duration and scene ID via the UI. What more do you need?

**Comment by blhoward2** [comment] 2021-09-15 22:49
That's assuming enough sceneId boxes show up. When I tried the Leviton before only half showed up. There are eight scenes as it sends a different one when turning off each button.

**Comment by MYeager1967** [comment] 2021-09-15 23:00
Last I looked, it only had one box to set anything in. The device has 7 buttons. 😀

**Comment by blhoward2** [comment] 2021-09-15 23:01
Try again with the new version, and upload a screenshot within zjs2mqtt please. And a node dump.

**Comment by MYeager1967** [comment] 2021-09-15 23:15
> Try again with the new version, and upload a screenshot within zjs2mqtt please. And a node dump.

Happily, but it will be at least tomorrow. How do I do the node dump? Your work on this is exceptional, especially since everyone else including open-zwave basically ignored it.

**Comment by MYeager1967** [comment] 2021-09-16 01:34
I'm not sure what command groups the device uses, but there's a few of us that would be more than happy to see this thing working so you should have plenty of help getting logs and such. I'll check this out tomorrow if I get time. I will have to update the container again first as I have the version that was reported to have an error and I may have to re-interview the device. I'll report back when I get that done.

**Comment by blhoward2** [comment] 2021-09-16 01:41
I don't have my devices hooked up anymore, but I think there should actually be two per group for the Leviton. It sends separate on/off scenes for each button, but each button has only one group.

**Comment by Ikcelaks** [comment] 2021-09-16 02:44
Thanks for that link! I'll check the specs more closely. It's possible that I interpreted things wrong, and we never noticed because we didn't have a device to test.

**Comment by Ikcelaks** [comment] 2021-09-16 03:28
Double checked the specs, and it very clearly stated that the number of groups should be retrieved using the `AssociationCC`, so there _shouldn't_be a distinction between scene groups and association groups, but obviously there is for your device according to the link you shared.

I wouldn't be shocked at all if other scene controllers followed the same pattern of having two (or more) scenes per association group. It should be relatively easy to dynamically determine the number of groups the `SceneControllerConfigurationCC` supports during the interview by simply performing a `Get` command on each `groupId` until we get a response `Report` for group 0. I imagine @AlCalzone would want that behind a compat flag.

**Comment by blhoward2** [comment] 2021-09-16 03:35
A manufacturer not follow the spec. I'm shocked! Shocked I tell you!

Seriously, though, I can build an image of whatever branch and test this on my test bench. So let me know when whatever you an Al decide is ready.

**Comment by AlCalzone** [comment] 2021-09-16 07:39
> It should be relatively easy to dynamically determine the number of groups the SceneControllerConfigurationCC supports during the interview by simply performing a Get command on each groupId until we get a response Report for group 0. I imagine @AlCalzone would want that behind a compat flag.

Hmm, interesting approach. In another issue we discussed specifying the actual number of scenes as a compat flag, but since we'll query each scene anyways (do we?), this should be okay. I'd still put it behind a flag to avoid unnecessary timeouts for confirming devices.

**Comment by Ikcelaks** [comment] 2021-09-16 19:00
The idea was that the first time we performed a `Get` asking an unsupported `groupId`, the node would tell us by replying with a `Report` for `groupId = 0`, which would tell us we'd gone past the end. However, I just took a look and saw that returning a `Report` with `groupId = 0` is only a "SHOULD" according to the specs. 👎 

Personally, I think it's a bad idea to depend on a timeout to tell us that we've queried all the valid `groupId`s. Let's go with having the compat flag explicitly set the number of groups.

**Comment by MYeager1967** [comment] 2021-09-16 19:12
I updated and re-interviewed the device and it looks like I still only get one scene select box. What can I do to help now?

**Comment by Ikcelaks** [comment] 2021-09-16 21:09
@MYeager1967 can you get the "Debug Info" for the node?

I'm surprised that you're only seeing one entry for Association Command Configuration, because the configuration file explicitly defines 7 association groups.

**Comment by MYeager1967** [comment] 2021-09-16 21:18
{
  "id": 44,
  "name": "Patio Scene Controller",
  "loc": "",
  "values": [
    {
      "id": "44-43-0-sceneId",
      "nodeId": 44,
      "commandClass": 43,
      "commandClassName": "Scene Activation",
      "endpoint": 0,
      "property": "sceneId",
      "propertyName": "sceneId",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Scene ID",
      "stateless": false,
      "min": 1,
      "max": 255,
      "list": false,
      "lastUpdate": 1631824163393
    },
    {
      "id": "44-43-0-dimmingDuration",
      "nodeId": 44,
      "commandClass": 43,
      "commandClassName": "Scene Activation",
      "endpoint": 0,
      "property": "dimmingDuration",
      "propertyName": "dimmingDuration",
      "type": "any",
      "readable": true,
      "writeable": true,
      "label": "Dimming duration",
      "stateless": false,
      "list": false,
      "lastUpdate": 1631824163394
    },
    {
      "id": "44-114-0-manufacturerId",
      "nodeId": 44,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "manufacturerId",
      "propertyName": "manufacturerId",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Manufacturer ID",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 282,
      "lastUpdate": 1631824163394,
      "newValue": 282
    },
    {
      "id": "44-114-0-productType",
      "nodeId": 44,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "productType",
      "propertyName": "productType",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Product type",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 2049,
      "lastUpdate": 1631824163394,
      "newValue": 2049
    },
    {
      "id": "44-114-0-productId",
      "nodeId": 44,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "productId",
      "propertyName": "productId",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Product ID",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 2819,
      "lastUpdate": 1631824163395,
      "newValue": 2819
    },
    {
      "id": "44-134-0-libraryType",
      "nodeId": 44,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "libraryType",
      "propertyName": "libraryType",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Library type",
      "stateless": false,
      "list": true,
      "states": [
        {
          "text": "Unknown",
          "value": 0
        },
        {
          "text": "Static Controller",
          "value": 1
        },
        {
          "text": "Controller",
          "value": 2
        },
        {
          "text": "Enhanced Slave",
          "value": 3
        },
        {
          "text": "Slave",
          "value": 4
        },
        {
          "text": "Installer",
          "value": 5
        },
        {
          "text": "Routing Slave",
          "value": 6
        },
        {
          "text": "Bridge Controller",
          "value": 7
        },
        {
          "text": "Device under Test",
          "value": 8
        },
        {
          "text": "N/A",
          "value": 9
        },
        {
          "text": "AV Remote",
          "value": 10
        },
        {
          "text": "AV Device",
          "value": 11
        }
      ],
      "value": 2,
      "lastUpdate": 1631824163395,
      "newValue": 2
    },
    {
      "id": "44-134-0-protocolVersion",
      "nodeId": 44,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "protocolVersion",
      "propertyName": "protocolVersion",
      "type": "string",
      "readable": true,
      "writeable": false,
      "label": "Z-Wave protocol version",
      "stateless": false,
      "list": false,
      "value": "3.42",
      "lastUpdate": 1631824163395,
      "newValue": "3.42"
    },
    {
      "id": "44-134-0-firmwareVersions",
      "nodeId": 44,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "firmwareVersions",
      "propertyName": "firmwareVersions",
      "type": "string[]",
      "readable": true,
      "writeable": false,
      "label": "Z-Wave chip firmware versions",
      "stateless": false,
      "list": false,
      "value": [
        "1.3"
      ],
      "lastUpdate": 1631824163396,
      "newValue": [
        "1.3"
      ]
    }
  ],
  "groups": [
    {
      "text": "Group 1",
      "endpoint": 0,
      "value": 1,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 2",
      "endpoint": 0,
      "value": 2,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 3",
      "endpoint": 0,
      "value": 3,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 4",
      "endpoint": 0,
      "value": 4,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 5",
      "endpoint": 0,
      "value": 5,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 6",
      "endpoint": 0,
      "value": 6,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    },
    {
      "text": "Group 7",
      "endpoint": 0,
      "value": 7,
      "maxNodes": 32,
      "isLifeline": false,
      "multiChannel": false
    }
  ],
  "neighbors": [],
  "ready": true,
  "available": true,
  "hassDevices": {},
  "failed": false,
  "inited": true,
  "hexId": "0x011a-0x0801-0x0b03",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x011a:0x0801:0x0b03:1.3",
  "manufacturerId": 282,
  "productId": 2819,
  "productType": 2049,
  "deviceConfig": {
    "filename": "/usr/src/app/store/.config-db/devices/0x011a/zwn-sc7.json",
    "isEmbedded": true,
    "manufacturer": "Wenzhou MTLC Electric Appliances Co., Ltd.",
    "manufacturerId": 282,
    "label": "ZWN-SC7",
    "description": "Scene Controller",
    "devices": [
      {
        "productType": 2049,
        "productId": 2819
      }
    ],
    "firmwareVersion": {
      "min": "0.0",
      "max": "255.255"
    },
    "associations": {}
  },
  "productLabel": "ZWN-SC7",
  "productDescription": "Scene Controller",
  "manufacturer": "Wenzhou MTLC Electric Appliances Co., Ltd.",
  "firmwareVersion": "1.3",
  "protocolVersion": 3,
  "nodeType": 0,
  "endpointsCount": 0,
  "endpointIndizes": [],
  "isSecure": false,
  "security": "None",
  "supportsSecurity": false,
  "supportsBeaming": true,
  "isControllerNode": false,
  "isListening": true,
  "isFrequentListening": false,
  "isRouting": false,
  "keepAwake": false,
  "maxDataRate": 40000,
  "deviceClass": {
    "basic": 2,
    "generic": 2,
    "specific": 2
  },
  "deviceId": "282-2819-2049",
  "status": "Alive",
  "interviewStage": "Complete",
  "statistics": {
    "commandsTX": 1,
    "commandsRX": 0,
    "commandsDroppedRX": 0,
    "commandsDroppedTX": 0,
    "timeoutResponse": 0
  },
  "lastActive": 1631824163396,
  "_name": "Patio Scene Controller"
}

**Comment by MYeager1967** [comment] 2021-09-16 21:22
![image](https://user-images.githubusercontent.com/4985590/133687414-f2dbe4f9-fe0d-4f48-b655-b888ba192fe4.png)

**Comment by MYeager1967** [comment] 2021-09-16 21:22
I'm assuming this is where I should see the multiple selection windows?

**Comment by AlCalzone** [comment] 2021-09-16 21:23
@MYeager1967 Please re-interview the device again, make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs), loglevel `debug` or `silly` and **attach** it here as a file.

The scene ID above is for Scene Activation CC (what the device sends the controller when a scene is activated), not the Scene XYZ Configuration CCs (which configure what the device sends).

**Comment by MYeager1967** [comment] 2021-09-16 21:32
Ok. I didn't edit anything out of the log so it's ALL there.... Hopefully you'll see something useful..
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/7181085/zwavejs2mqtt.log)
.

**Comment by AlCalzone** [comment] 2021-09-16 21:36
That's not a driver log. Check my link.

**Comment by MYeager1967** [comment] 2021-09-16 22:07
> That's not a driver log. Check my link.

Right switches, wrong section. Sorry.... I promise I'm capable of learning.... This is the log you're looking for!

[zwavejs_2021-09-16.log](https://github.com/zwave-js/zwavejs2mqtt/files/7181218/zwavejs_2021-09-16.log)

**Comment by AlCalzone** [comment] 2021-09-17 07:13
So, the device does actually support 7 association groups, not 4 like that other controller. However your log contains a bunch of these messages
> [Node 044] Timed out while waiting for a response from the node

meaning the driver doesn't get any response at all to some queries. This includes the queries of the CC versions and the entirety of Scene Controller Configuration CC.

**Comment by MYeager1967** [comment] 2021-09-17 12:30
I found this a while back on another site:

ZWN-­‐SC7    has    7    association    groups.
Here is a sample instruction how to implement a button for a scene. Reader should better be a zwave software programmer. 

1. Include the ZWN-­‐SC7 in a z‐wave gateway controller.
2. Set up an association group for ZWN-­‐SC7. Use CC_ASSOCIATION. We suggest assign the controller’s nodeID into the group for later use.
3. Use CC_SCENE_CONTROLLER_CONF to assign the scene in the gateway controller to the ZWN-­‐SC7’s button. For command SCENE_CONTROLLER_CONF_SET, parameter groupID is the ZWN-­‐SC7’s asscoation groupID. sceneID is the identity of the scene in you gateway controller.
4. Press ZWN-­‐SC7 button to test the scene.

I've been told repeatedly over time that this device doesn't seem to follow the standard very well. On the Vera controller, it includes and then you have to go into the setup for the device and point it to the scenes. In the log, it's not getting an answer to the scene controller conf query but is it possible that the controller isn't answering because it's not expecting it and the format is wrong? I'm just spitballing here as this project is way over my head.

**Comment by AlCalzone** [comment] 2021-09-17 13:27
1. is already done since you have the device included
2. is also done during the first interview (confirmed by your log)
3. is what I proposed above

> In the log, it's not getting an answer to the scene controller conf query but is it possible that the controller isn't answering because it's not expecting it and the format is wrong?

The format is very simple: just the normal CC header (like for every other CC) plus 1 byte group ID. Hard to get that wrong, so I'd say the device just doesn't follow the specs and only implements partial support for the CC (just setting, not reading the config).

If that's the case, don't worry about the timeouts after you're setting the scenes (if the SET command goes through).

**Comment by csanner** [comment] 2021-09-17 16:38
so how would I run that custom driver function?
Also, is this, by nature of being a "scene controller", limited to setting a "scene" - i.e. is there no way to read an incoming zwave message in, say, node-red and act on that?

**Comment by Ikcelaks** [comment] 2021-09-17 17:12
@MYeager1967 and anyone else who is trying to use a scene controller that has already been setup in the past, if your scene controller has always sent scene activation commands to the controller/hub (not directly to other nodes), you probably just need to add your controller (probably node_1) to EVERY association group on the scene controller node.

Then you can listen for the scene activation events in home assistant or whatever system you're using.

**Comment by AlCalzone** [comment] 2021-09-17 17:28
> Also, is this, by nature of being a "scene controller", limited to setting a "scene" - i.e. is there no way to read an incoming zwave message in, say, node-red and act on that?

A scene controller **activates** scenes in other devices using the `Scene Activation CC`. You'll see which scene was activated and its duration via this value:
https://github.com/zwave-js/zwavejs2mqtt/issues/1640#issuecomment-921256206


> so how would I run that custom driver function?

![driver function](https://user-images.githubusercontent.com/17641229/133829254-ac0bfd44-aaf2-44d2-8a18-dbb99dec14a6.gif)

or using a `sendCommand` MQTT API call:
https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=send-command
with this payload (or similar)
```jsonc
{
	"args": [
		{
			"nodeId": 44,
			"commandClass": 0x2d,
			"endpoint": 0,
		},
		"set",
		[
			1, // group id
			5, // scene id,
			"2m", // duration
		]
	]
}
```

**Comment by csanner** [comment] 2021-09-17 19:38
ah.
I'm still unable to get the MQTT zwave_js working.

**Comment by MYeager1967** [comment] 2021-09-17 19:51
The way I understand it, the step missing here is assigning a scene to each of the 7 buttons on the controller itself. I've already added node 1 to all the association groups and when pushing buttons, nothing seems to show up anywhere (might be something in the driver log, I haven't looked there yet). Since nothing shows up in MQTT or the MQTT Event stream, I have nothing to act on. I'm guessing at this point that since there's nothing assigned to the buttons, it has nothing to send. This device never passed compliance for Z-wave and definitely doesn't adhere to all of the standard. 😀 We seem to be getting closer to getting it functional by the day though. May be a few days before I have much time to play with this again but I'll try to look at the driver command route before I leave for work in the morning.

**Comment by Ikcelaks** [comment] 2021-09-17 19:56
@MYeager1967 Did you follow Al's instructions for running the custom driver function? If you do that for each of the scenes 1 through 7, I'm optimistic you'll start seeing events coming in.

**Comment by MYeager1967** [comment] 2021-09-17 20:00
I haven't had the opportunity yet. I'm assuming I just increment the group number (1-7) and assign the appropriate scene number. Will try to get to it in the morning, won't have much time though.

**Comment by Ikcelaks** [comment] 2021-09-17 20:06
Yeah, that's what the old SmartThings custom integration did. It shouldn't even matter what you set the `dimmingDuration` to, since you're just going to listen for events with the controller. That's ironic, because I originally popped in here to talk about fixing that bug.

**Comment by MYeager1967** [comment] 2021-09-17 20:08
Would be nice if the GUI detected this device and presented seven drop downs to assign the scenes, but I'm ok with doing it manually if it works. The author has already done way more than anyone else has in three years or so to get this working with HA.

**Comment by AlCalzone** [comment] 2021-09-17 20:20
> Would be nice if the GUI detected this device and presented seven drop downs to assign the scenes, but I'm ok with doing it manually if it works.

We usually avoid doing device specific workarounds in the driver if there is another way. What you want **might** be possible with the compat flag we discussed 2 days ago, because then the 7 values you should be seeing should show up (like they should if the device behaved correctly).

**Comment by MYeager1967** [comment] 2021-09-17 20:44
I understand not doing device specific workarounds. You'd have to store the data in the program itself as it appears you possibly can't get it from the device. Hopefully, the driver command route will do the trick

**Comment by MYeager1967** [comment] 2021-09-18 12:38
![image](https://user-images.githubusercontent.com/4985590/133889062-5d79f145-1190-4641-9cd8-8031cf0355b9.png)

I don't seem to have the driver function option under advanced on my controller tab.... Is there something I need to change to get it?

**Comment by Ikcelaks** [comment] 2021-09-18 12:42
@MYeager1967 "Driver function" isn't under the node. Go to the "Actions" box at the top of the Control Panel, click "Advanced", and you'll find it there.

**Comment by MYeager1967** [comment] 2021-09-18 12:53
Found it! I figured it would be under the controller and the quick little video apparently didn't help me out. Just tried to write them the hard way from MQTT. Will test it real quick on my way out the door. Probably should have enabled logging again but I didn't. Will do that if I have to do it all again...

**Comment by AlCalzone** [comment] 2021-09-18 19:19
> I have no idea what to do with the other!

Is my post above containing the exact command not enough?
https://github.com/zwave-js/zwavejs2mqtt/issues/1640#issuecomment-921556785

**Comment by MYeager1967** [comment] 2021-09-18 20:04
> > I have no idea what to do with the other!
> 
> Is my post above containing the exact command not enough?
> [#1640 (comment)](https://github.com/zwave-js/zwavejs2mqtt/issues/1640#issuecomment-921556785)

I somehow missed that one and caught the MQTT part of the post. It's been a long couple of days at work and I'll admit that I haven't been the sharpest tool in the shed the past few days. I'll be extremely happy to run that in the morning. Will it show up in the log at all of should I bother trying to log it?

**Comment by AlCalzone** [comment] 2021-09-18 20:06
It should, yes.

**Comment by MYeager1967** [comment] 2021-09-18 20:07
Great! I'll give it a go and report back..

**Comment by MYeager1967** [comment] 2021-09-19 04:07
Had to leave off the optional line to get the commands to send, but they show up in the log with a transmit status of OK. Will be interesting to play with it in the morning to see what I get for messages that I can act on... Getting there!!!!!

**Closed** 2021-09-19 12:11 UTC
Labels: question

**Comment by MYeager1967** [comment] 2021-09-19 12:26
While I'm happy to see an issue closed, this controller still isn't working properly. Probably never will though.....

**Comment by AlCalzone** [comment] 2021-09-19 12:31
@Ikcelaks's PR was just merged, which adds the 7 values for you to configure it from the UI. Can you share the current association setup of your device please?

**Comment by AlCalzone** [comment] 2021-09-19 12:35
According to this [SmartThings device handler](https://github.com/mwav3/smartthingscode/blob/master/devicetypes/mwav3/zwnsc7-enerwave-scene-master.src/zwnsc7-enerwave-scene-master.groovy), each scene must be set up to use the corresponding association group. So group 1 scene 1; group 2 scene 2; ...

**Comment by MYeager1967** [comment] 2021-09-19 12:37
I have seven groups that have node 1 in them. If you want the actual JSON
dump or something, I'll get it for you tomorrow morning. I'm off and
running already today. Pressed a button this morning and got the standard
all lights flash..  😐

**Comment by MYeager1967** [comment] 2021-09-19 12:40
> According to this [SmartThings device handler](https://github.com/mwav3/smartthingscode/blob/master/devicetypes/mwav3/zwnsc7-enerwave-scene-master.src/zwnsc7-enerwave-scene-master.groovy), each scene must be set up to use the corresponding association group. So group 1 scene 1; group 2 scene 2; ...

Though I handled that last night with the driver commands. Let me know what you need to see and I'll get it to you. Will update again tomorrow and see if that helps.

**Comment by AlCalzone** [comment] 2021-09-19 12:45
> I have seven groups that have node 1 in them

That sounds correct. 

> Let me know what you need to see and I'll get it to you.

Let's start with a driver log where you run the driver commands again. After that, press the device's buttons and capture that in the same log (if anything happens at all).

**Comment by blhoward2** [comment] 2021-09-19 17:51
> According to this [SmartThings device handler](https://github.com/mwav3/smartthingscode/blob/master/devicetypes/mwav3/zwnsc7-enerwave-scene-master.src/zwnsc7-enerwave-scene-master.groovy), each scene must be set up to use the corresponding association group. So group 1 scene 1; group 2 scene 2; ...

I'm not sure that's right. Mine were setup groups 1-8, scene 1 per the link above.

**Comment by MYeager1967** [comment] 2021-09-20 15:58
Ok. Here's where I stand now. The commands sent to the controller were as such:

await driver.controller.nodes.get(44).commandClasses["Scene Controller Configuration"].set(
  1, // this is the group #
  1, // this is the scene ID it should send
)

With the extra line present, it threw an error. That said, the scene controller now acts like it's working. The button press give the three flashes and the steady light next to the active button. However, I'm getting nothing in the log when I press any of the buttons. I had to open the door to look and see if the scene turned on the light (it's daytime here) and I then manually activated the scene from the UI to make sure I hadn't screwed it up. The scene works when manually activated. So close!!!
[zwavejs_2021-09-20.log](https://github.com/zwave-js/zwavejs2mqtt/files/7197009/zwavejs_2021-09-20.log)

**Comment by MYeager1967** [comment] 2021-09-20 16:03
> You won’t see anything in the log unless you put the controller in each association group as I recall. Brian

The log has entries in it, it just took a bit for them to show up in my monitor window. I edited the post with that and a better log. The device is working, now it's an issue of why it's not firing the scene.

**Comment by MYeager1967** [comment] 2021-09-20 16:07
This is the current scene list if it helps spot a problem..
[scenes.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/7197074/scenes.json.txt)
.

**Comment by blhoward2** [comment] 2021-09-20 16:37
That’s not how these work. The Scene inside zjs2mqtt has nothing to do with the scene event the device is sending out. You’d need to automate off the scene message coming in and have HA or whatever fire the scene.

**Comment by MYeager1967** [comment] 2021-09-20 16:46
Gotcha. Can I build the scenes in zwavejs2mqtt or do I build them in HA? Each scene has multiple devices in it and this device only sends an "on", there is no off. That being the case, unless there's a way to specify the desired state in a direct association, I'm out of luck....

**Comment by blhoward2** [comment] 2021-09-20 16:48
I don't believe so. You may be able to activate the scene in zjs2mqtt through mqtt but that would be it. It would be cleaner just to do it where you're automating. 

With the VRCS4, it restores the device to whatever state/level it was in when you added it as I recall. It's not perfect.

**Comment by MYeager1967** [comment] 2021-09-20 22:57
Success! I managed to figure out how to grab the data I needed from the node_value_updated key buried under events. I used this to automate the scenes that I originally had assigned to this switch. It's still a temperamental little bastard, sometimes needing several presses before it registers, but I think that may be a locational thing. Either way... Was there supposed to be a newer version with the scene setting in the GUI? As of early this morning, I hadn't seen it.

**Comment by AlCalzone** [comment] 2021-09-20 23:12
No its not released yet

**Comment by MYeager1967** [comment] 2021-09-20 23:30
Ok. I look forward to seeing it. Any idea why the data from the event stream isn't populated into the MQTT data tree? It puts the 44/43/0/sceneId entry in, but only time shows. There's quite a bit more under 43/0/sceneId.....

**Comment by AlCalzone** [comment] 2021-09-21 06:21
@robertsLando ?

**Comment by robertsLando** [comment] 2021-09-21 06:30
@MYeager1967 Are you using Mqtt explorer? BTW I publish everything I receive as valueId and notifications to mqtt, you should enable debug logs and check when the event occurs if you see the log that shows the publish

**Comment by MYeager1967** [comment] 2021-09-21 11:24
> @MYeager1967 Are you using Mqtt explorer? BTW I publish everything I receive as valueId and notifications to mqtt, you should enable debug logs and check when the event occurs if you see the log that shows the publish

Absolutely running MQTT Explorer. Wouldn't be without it. This is the entire tree for the device. Unfortunately, there's nothing in the last line that's useful either... I'll Try to check the debug for that later. Right now, I'm working off the event itself. Would be much better if it showed up in the tree. I'm guessing it's probably got something to do with the device itself though...
![Capture](https://user-images.githubusercontent.com/4985590/134161853-46015c5f-5ebb-45cf-b87a-e2403e8adeab.PNG)

**Comment by AlCalzone** [comment] 2021-09-21 11:33
By the driver, `sceneId` is treated as an event and not a persisted value. I think zwavejs2mqtt resets the values it creates for those back to `undefined` after a second, @robertsLando ?

**Comment by MYeager1967** [comment] 2021-09-21 12:00
No idea. It doesn't show up in the data tree anywhere so I can't even tell you it's undefined.

**Comment by AlCalzone** [comment] 2021-09-21 12:04
![grafik](https://user-images.githubusercontent.com/17641229/134167167-478bf6f0-4f38-4a51-97da-03a9bb01c727.png)
What about this?

**Comment by MYeager1967** [comment] 2021-09-21 12:07
That's part of the data. There's quite a bit more under that key...

**Comment by MYeager1967** [comment] 2021-09-21 12:20
When I get back on the computer later, I'll copy the whole event that I'm catching. There's plenty there..

**Comment by jim0020** [comment] 2022-01-19 20:50
Has anyone documented the steps to make this device work?  Thanks in advance.

**Comment by MYeager1967** [comment] 2022-01-19 22:03
The way I got it working is documented in this thread. They have since made it easier by moving it into the GUI. I haven't updated to that method yet....
