### ISSUE TITLE
[bug] Value change not reflected in UI or to HASS

### ISSUE THREAD

**Issue by gbillyb** [zwave-js/zwavejs2mqtt#1522] opened 2021-08-02 05:15 UTC
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.4.3
zwave-js version: 8.0.6

### Describe the bug

Turning on or off a switch 1 on a **Fibaro FGS211 / FGS221 Double Relay Switch 2x1.5kW** does not update the state in the UI or HASS.

### To Reproduce

(from 2021-08-02T05:01:19.745Z in the Driver logs)

1. Expand the Node in the UI
2. Click on Binary Switch to see the current values
3. Click Refresh to be sure
4. [12-37-1-currentValue] Current value : false
5. [12-37-2-currentValue] Current value : false
6. Turn on the device (switch 1)
7. [12-37-1-currentValue] Current value : false
8. Turn on the device (switch 2)
9. [12-37-2-currentValue] Current value : true

### Expected behavior
Switch 1 should behave the same as switch 2 and report the state change.

### Additional context

All of the above was performed after a restart of Z2M and a re-interview of the node.

![image](https://user-images.githubusercontent.com/25873470/127806834-3345e02d-85de-46cd-a310-76860c42f4c7.png)
[node_12.json.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6914480/node_12.json.zip)
[zwavejs_2021-08-02.log](https://github.com/zwave-js/zwavejs2mqtt/files/6914472/zwavejs_2021-08-02.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6914473/zwavejs2mqtt.log)

**Comment by robertsLando** [comment] 2021-08-02 07:41
@AlCalzone

**Comment by AlCalzone** [comment] 2021-08-02 07:46
Duplicate of https://github.com/zwave-js/node-zwave-js/issues/3119

**Closed** 2021-08-10 07:00 UTC
Labels: bug
