### ISSUE TITLE
[question]  Fibaro Dimmer FBG212 OFF message does not set current value to 0

### ISSUE THREAD

**Issue by graphicsxp** [zwave-js/zwavejs2mqtt#2362] opened 2022-04-10 12:36 UTC
I want to programmatically turn off the light connected to a FIbaro Dimmer 2 FBG212.

I could send a message to 
zwave/light-dressing/38/1/currentValue/set with payload {"value" : 0}  and that'd work.

But I noticed in MQTT explorer there is also an endpoint to turn it off :

![image](https://user-images.githubusercontent.com/4160415/162618471-4683a510-3633-4d56-84fd-15bace47b639.png)

However when sending that message, it dims down the bulb to 7 but not 0. 

The same occurs if I perform the level change from zwavejs2mqtt UI : 

![image](https://user-images.githubusercontent.com/4160415/162618440-2e04245d-58cf-4e61-9318-87e45b0479bc.png)

Is this a bug ?

**Comment by robertsLando** [comment] 2022-04-11 07:24
Duplicate of https://github.com/zwave-js/zwavejs2mqtt/discussions/2360

Please follow updates there

**Closed** 2022-04-11 07:24 UTC
Labels: question
